### ISSUE TITLE
API: ExecutionResult can't handle large XML files

### ISSUE THREAD

**Issue by molsky** [robotframework/robotframework#2199]
Tried to read results from XML but it fails with large XML files (in my case XML file contains over 170.000 lines). With smaller XML this error doesn't exists (tested with XML output files that have less than 30.000 lines).

```
Traceback (most recent call last):
  File "keywordtimes.py", line 125, in <module>
    resu = ExecutionResult('output.xml')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robot/result/resultbuilder.py", line 44, in ExecutionResult
    return _single_result(sources[0], options)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robot/result/resultbuilder.py", line 68, in _single_result
    raise DataError("Reading XML source '%s' failed: %s" % (unicode(ets), error))
robot.errors.DataError: Reading XML source 'output.xml' failed: ParseError: no element found: line 177272, column 75
```
Robot Framework version: 2.9.2

**Comment by molsky** [comment]
Downloaded it again and works fine. So it was corrupted somehow even it looked fine when checked content with text editor. Closing this as invalid.
