### ISSUE TITLE
Installation error in CentOS 7 + Python 3.4, RF 2.9.2

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/robotframework#2277]
This is the output (in a fresh python 3.4 + pip3 install):
```
[helio@centos7 Download]$ pip3 list
pip (7.1.2)
setuptools (19.1.1)
wheel (0.26.0)
[helio@centos7 Download]$ sudo pip3 install robotframework
Collecting robotframework
  Downloading robotframework-2.9.2.tar.gz (424kB)
    100% |████████████████████████████████| 425kB 234kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-zekek279/robotframework/setup.py", line 51
        for directory in 'rebot', 'libdoc', 'testdoc', 'lib', 'common'
                                ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-zekek279/robotframework
```

**Comment by pekkaklarck** [comment]
Yeah, RF < 3.0, including `setup.py`, doesn't support Python 3 at all. `pip3 install --pre robotframework` ought to install 3.0a2 that is Python 3 compatible.
