### ISSUE TITLE
UnicodeDecodeError when file path has non 'ascii' character

### ISSUE THREAD

**Issue by gualber98** [robotframework/robotframework#2308]
My home directory path has an 'ñ' in the name and when I run a pybot I get the following error because it cannot decode byte 0xf1 

`
[ ERROR ] Unexpected error: UnicodeDecodeError: 'ascii' codec can't decode byte 0xf1 in position 63: ordinal not in range(128)
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robot\utils\application.py", line 80, in _execute
    rc = self.main(arguments, **options)
  File "C:\Python27\lib\site-packages\robot\run.py", line 434, in main
    result = suite.run(settings)
  File "C:\Python27\lib\site-packages\robot\running\model.py", line 247, in run
    self.visit(runner)
  File "C:\Python27\lib\site-packages\robot\model\testsuite.py", line 160, in visit
    visitor.visit_suite(self)
  File "C:\Python27\lib\site-packages\robot\model\visitor.py", line 83, in visit_suite
    if self.start_suite(suite) is not False:
  File "C:\Python27\lib\site-packages\robot\running\runner.py", line 72, in start_suite
    ns.handle_imports()
  File "C:\Python27\lib\site-packages\robot\running\namespace.py", line 54, in handle_imports
    self._handle_imports(self._imports)
  File "C:\Python27\lib\site-packages\robot\running\namespace.py", line 65, in _handle_imports
    self._import(item)
  File "C:\Python27\lib\site-packages\robot\running\namespace.py", line 73, in _import
    action(import_setting)
  File "C:\Python27\lib\site-packages\robot\running\namespace.py", line 86, in _import_resource
    self._handle_imports(resource.imports)
  File "C:\Python27\lib\site-packages\robot\running\namespace.py", line 65, in _handle_imports
    self._import(item)
  File "C:\Python27\lib\site-packages\robot\running\namespace.py", line 73, in _import
    action(import_setting)
  File "C:\Python27\lib\site-packages\robot\running\namespace.py", line 86, in _import_resource
    self._handle_imports(resource.imports)
  File "C:\Python27\lib\site-packages\robot\running\namespace.py", line 65, in _handle_imports
    self._import(item)
  File "C:\Python27\lib\site-packages\robot\running\namespace.py", line 73, in _import
    action(import_setting)
  File "C:\Python27\lib\site-packages\robot\running\namespace.py", line 127, in _import_library
    import_setting.alias, self.variables)
  File "C:\Python27\lib\site-packages\robot\running\importer.py", line 41, in import_library
    lib = TestLibrary(name, args, variables, create_handlers=False)
  File "C:\Python27\lib\site-packages\robot\running\testlibraries.py", line 49, in TestLibrary
    return_source=True)
  File "C:\Python27\lib\site-packages\robot\utils\importer.py", line 71, in import_class_or_module
    self._raise_import_failed(name, err)
  File "C:\Python27\lib\site-packages\robot\utils\importer.py", line 107, in _raise_import_failed
    raise DataError('\n'.join(msg))
`

**Comment by pekkaklarck** [comment]
- Which RF version? If not 3.0, please test with that version.
- Do you get this always when running tests or only with certain data? The included traceback seems to be about library import.

**Comment by pekkaklarck** [comment]
Any more information about this?

**Comment by pekkaklarck** [comment]
Closing due to lack of information.
