### ISSUE TITLE
robot framework 2.0a

### ISSUE THREAD

**Issue by autoguy** [robotframework/robotframework#2313]
- edit keys do not seem to work.
- tried select all -- see below.

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotframework_ride-2.0a1-py2.7.egg\robotide\ui\actiontriggers.py", line 377, in __call__
    action.act(event)
  File "C:\Python27\lib\site-packages\robotframework_ride-2.0a1-py2.7.egg\robotide\action\action.py", line 86, in act
    self.action(event)
  File "C:\Python27\lib\site-packages\robotframework_ride-2.0a1-py2.7.egg\robotide\log\log.py", line 101, in <lambda>
    'CtrlCmd-A', lambda e: self._window.SelectAll())
AttributeError: '_LogWindow' object has no attribute 'SelectAll'
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotframework_ride-2.0a1-py2.7.egg\robotide\ui\actiontriggers.py", line 377, in __call__
    action.act(event)
  File "C:\Python27\lib\site-packages\robotframework_ride-2.0a1-py2.7.egg\robotide\action\action.py", line 86, in act
    self.action(event)
  File "C:\Python27\lib\site-packages\robotframework_ride-2.0a1-py2.7.egg\robotide\log\log.py", line 101, in <lambda>
    'CtrlCmd-A', lambda e: self._window.SelectAll())
AttributeError: '_LogWindow' object has no attribute 'SelectAll'
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotframework_ride-2.0a1-py2.7.egg\robotide\ui\actiontriggers.py", line 377, in __call__
    action.act(event)
  File "C:\Python27\lib\site-packages\robotframework_ride-2.0a1-py2.7.egg\robotide\action\action.py", line 86, in act
    self.action(event)
  File "C:\Python27\lib\site-packages\robotframework_ride-2.0a1-py2.7.egg\robotide\log\log.py", line 101, in <lambda>
    'CtrlCmd-A', lambda e: self._window.SelectAll())
AttributeError: '_LogWindow' object has no attribute 'SelectAll'
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotframework_ride-2.0a1-py2.7.egg\robotide\ui\actiontriggers.py", line 377, in __call__
    action.act(event)
  File "C:\Python27\lib\site-packages\robotframework_ride-2.0a1-py2.7.egg\robotide\action\action.py", line 86, in act
    self.action(event)
  File "C:\Python27\lib\site-packages\robotframework_ride-2.0a1-py2.7.egg\robotide\log\log.py", line 101, in <lambda>
    'CtrlCmd-A', lambda e: self._window.SelectAll())
AttributeError: '_LogWindow' object has no attribute 'SelectAll'

C:\Users\auto\branch\UserManagement>

**Comment by HelioGuilherme66** [comment]
Wrong issue tracker. You should open issue in [RIDE](https://github.com/robotframework/RIDE/issues) and change the name to the correct application and problem.
Also please give more info on what OS version you use (we can see it is Windows), also what wxPython version.

Please detail what you were doing when the problem happened. On a quick look, looks that you were trying to edit in the Log Window (is it RIDE's or test runner's?), and the CTRL-A also fails there.
