### ISSUE TITLE
Execution crashes if tests are run with `--output NONE` and any test or keyword has timeout

### ISSUE THREAD

**Issue by joanna-may** [robotframework/robotframework#2326]
```robotframework
*** Settings ***
Library         String
Library         Collections

*** Test Cases ***
first failing test
  Get Current Date

run keyword 1
  No Operation

run keyword 2
  Add 1 and return  50

test wich change status from fail to pass - this is special long name for execution view
  Pass Execution  lol
  Fail  This will be not shown

pass case before fatal error
  Get Line Count  here is string with \n 2 lines

here is fatal error
  FATAL error  Big kaboom!!!

pass case after fatal error
  Log  This will be not shown
  Should Not End With  red hot hot

*** Keywords ***
Add 1 and return
  [Arguments]  ${a}
  [Documentation]  This is documentation
  ...  With new line
  [Timeout]  50 seconds
  ${b} =  set variable  ${1}
  ${calculatedValue} =  Evaluate  ${a}+${b}
  [Return]  ${calculatedValue}
```
RF: 3.0
Python: 2.7.8
When running this script with arguments:
--output NONE --report NONE --log NONE
I have error below. With no argument this works.
```
Jjjj                                                                                                                                                                  
======================================================================================================================================================================
first failing test                                                                                                                                            | FAIL |
No keyword with name 'Get Current Date' found.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
run keyword 1                                                                                                                                                 | PASS |
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
run keyword 2                                                                                                                                                 unexpected error: [ ERROR ] Unexpected error: TypeError: <lambda>() got an unexpected keyword argument 'attrs'
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\robot\utils\application.py", line 80, in _execute
    rc = self.main(arguments, **options)
  File "c:\Python27\lib\site-packages\robot\run.py", line 434, in main
    result = suite.run(settings)
  File "c:\Python27\lib\site-packages\robot\running\model.py", line 247, in run
    self.visit(runner)
  File "c:\Python27\lib\site-packages\robot\model\testsuite.py", line 160, in visit
    visitor.visit_suite(self)
  File "c:\Python27\lib\site-packages\robot\model\visitor.py", line 86, in visit_suite
    suite.tests.visit(self)
  File "c:\Python27\lib\site-packages\robot\model\itemlist.py", line 69, in visit
    item.visit(visitor)
  File "c:\Python27\lib\site-packages\robot\model\testcase.py", line 73, in visit
    visitor.visit_test(self)
  File "c:\Python27\lib\site-packages\robot\running\runner.py", line 134, in visit_test
    test.template).run_steps(test.keywords.normal)
  File "c:\Python27\lib\site-packages\robot\running\steprunner.py", line 35, in run_steps
    self.run_step(step)
  File "c:\Python27\lib\site-packages\robot\running\steprunner.py", line 56, in run_step
    return runner.run(step, context)
  File "c:\Python27\lib\site-packages\robot\running\userkeywordrunner.py", line 54, in run
    return return_value
  File "c:\Python27\lib\site-packages\robot\running\statusreporter.py", line 53, in __exit__
    context.end_keyword(result)
  File "c:\Python27\lib\site-packages\robot\running\context.py", line 178, in end_keyword
    self.output.end_keyword(keyword)
  File "c:\Python27\lib\site-packages\robot\output\output.py", line 64, in end_keyword
    LOGGER.end_keyword(kw)
  File "c:\Python27\lib\site-packages\robot\output\logger.py", line 194, in end_keyword
    logger.end_keyword(keyword)
  File "c:\Python27\lib\site-packages\robot\output\xmllogger.py", line 80, in end_keyword
    self._writer.element('timeout', attrs={'value': unic(kw.timeout)})

test finished 20160229 14:28:18
```

**Comment by HelioGuilherme66** [comment]
I confirm this BUG.
It happens if there is the Timeout set and those options. If you remove the Timeout no BUG.
Following is a run with Timeout at "1 second" and loglevel TRACE:
```
Starting test: Bug 2326.first failing test
20160229 14:15:23.705 :  FAIL : No keyword with name 'Get Current Date' found.
Ending test:   Bug 2326.first failing test

Starting test: Bug 2326.run keyword 1
20160229 14:15:23.708 : TRACE : Arguments: [  ]
20160229 14:15:23.708 : TRACE : Return: None
Ending test:   Bug 2326.run keyword 1

Starting test: Bug 2326.run keyword 2
20160229 14:15:23.711 : TRACE : Arguments: [ ${a}='50' ]
20160229 14:15:23.712 : TRACE : Arguments: [ 1 ]
20160229 14:15:23.713 : DEBUG : Keyword timeout 1 second active. 0.999 seconds left.
20160229 14:15:23.713 : TRACE : Return: 1
20160229 14:15:23.713 :  INFO : ${b} = 1
20160229 14:15:23.714 : TRACE : Arguments: [ '50+1' ]
20160229 14:15:23.715 : DEBUG : Keyword timeout 1 second active. 0.997 seconds left.
20160229 14:15:23.716 : TRACE : Return: 51
20160229 14:15:23.716 :  INFO : ${calculatedValue} = 51
20160229 14:15:23.717 : TRACE : Return: 51
```

**Comment by pekkaklarck** [comment]
Thanks for the report. As @HelioGuilherme66 already analysed, the bug occurs only if a test or keyword has a timeout and `--output NONE` is used. Although this is a pretty rare combination, this kind of a crash is always severe and this issue deserves high priority. Not high enough to demand an immediate 3.0.1 release, though.

The root cause is that [NullMarkupWriter](https://github.com/robotframework/robotframework/blob/master/src/robot/utils/markupwriters.py#L103) methods only accept `*args` and when there are timeouts they are used like `element('timeout', attrs={'value': unic(kw.timeout)})`. A fix is changing `NullMarkupWriter` methods to accept `*args, **kwargs` instead.

**Comment by kormbrek-rally** [comment]
We seem to have gotten bit by this from using pabot. We use pabot 0.24, which does not do `--output NONE`, but does do `--log NONE`, `--report NONE`, and `--xunit NONE` when calling Robot Framework.
We removed the usage of timeouts.

After removing variables arguments (for brevity), the call looks like this:
`pabot  --processes 8 --noncritical non-critical --loglevel ERROR --include completeSurveyVerifyDataORC25217 --exclude NONE`.
The resulting call to RF (after removing variables arguments for brevity) is:
`pybot --exclude NONE --outputdir ./pabot_results/Core-AutomatedTests.API.Data2.Survey.SurveyWithNewKeyword --log NONE --loglevel ERROR --consolecolors off --noncritical non-critical --report NONE --consolemarkers off --xunit NONE --suite Core-AutomatedTests.API.Data2.Survey.SurveyWithNewKeyword --include completeSurveyVerifyDataORC25217 ./`

**Comment by pekkaklarck** [comment]
Does 3.0.1 fix the problem for you?

**Comment by kormbrek-rally** [comment]
Had not realized 3.0.1 was already out. Yes it does resolve the problem. Thanks!
