### ISSUE TITLE
Unit tests only pass in specific order

### ISSUE THREAD

**Issue by philsc** [robotframework/robotframework#2332]
When running the robotframework unit tests on our test servers, they will occasionally fail with strange failures. I'm quite convinced that there is some problem with unit tests affecting one another somehow.

Easy way to reproduce this:

``` patch
diff --git a/utest/run.py b/utest/run.py
index e501942..cbfc3a6 100755
--- a/utest/run.py
+++ b/utest/run.py
@@ -18,6 +18,7 @@ import os
 import sys
 import re
 import getopt
+import random


 base = os.path.abspath(os.path.normpath(os.path.split(sys.argv[0])[0]))
@@ -34,7 +35,9 @@ def get_tests(directory=None):
         directory = base
     sys.path.insert(0, directory)
     tests = []
-    for name in os.listdir(directory):
+    names = os.listdir(directory)
+    random.shuffle(names)
+    for name in names:
         if name.startswith("."): continue
         fullname = os.path.join(directory, name)
         if os.path.isdir(fullname):
```

Then run the unit tests 20 times:

``` bash
for i in {1..20}; do python ./utest/run.py ; done
```

And you'll see errors like this:

```
======================================================================
FAIL: test_custom_stdout (test_run_and_rebot.TestRebot)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philipp/repos/robotframework/utest/api/test_run_and_rebot.py", line 176, in test_custom_stdout
    self._assert_outputs()
  File "/home/philipp/repos/robotframework/utest/resources/runningtestcase.py", line 40, in _assert_outputs
    self._assert_output(sys.__stderr__, stderr)
  File "/home/philipp/repos/robotframework/utest/resources/runningtestcase.py", line 50, in _assert_output
    self._assert_no_output(output)
  File "/home/philipp/repos/robotframework/utest/resources/runningtestcase.py", line 54, in _assert_no_output
    raise AssertionError('Expected output to be empty:
%s' % output)
AssertionError: Expected output to be empty:
[ ERROR ] Adding keyword 'Many Args' to library 'classes.InvalidGetArgsDynamicLibrary' failed: Calling dynamic method 'get_keyword_arguments' failed: ZeroDivisionError: integer division or modulo by zero
[ ERROR ] Adding keyword 'No Arg' to library 'classes.InvalidGetArgsDynamicLibrary' failed: Calling dynamic method 'get_keyword_arguments' failed: ZeroDivisionError: integer division or modulo by zero
[ ERROR ] Adding keyword 'No Arg Spec' to library 'classes.InvalidGetArgsDynamicLibrary' failed: Calling dynamic method 'get_keyword_arguments' failed: ZeroDivisionError: integer division or modulo by zero
[ ERROR ] Adding keyword 'One Arg' to library 'classes.InvalidGetArgsDynamicLibrary' failed: Calling dynamic method 'get_keyword_arguments' failed: ZeroDivisionError: integer division or modulo by zero
[ ERROR ] Adding keyword 'One or Two Args' to library 'classes.InvalidGetArgsDynamicLibrary' failed: Calling dynamic method 'get_keyword_arguments' failed: ZeroDivisionError: integer division or modulo by zero
[ ERROR ] Adding keyword 'Many Args' to library 'classes.InvalidGetDocDynamicLibrary' failed: Calling dynamic method 'get_keyword_documentation' failed: TypeError: get_keyword_documentation() takes exactly 3 arguments (2 given)
[ ERROR ] Adding keyword 'No Arg' to library 'classes.InvalidGetDocDynamicLibrary' failed: Calling dynamic method 'get_keyword_documentation' failed: TypeError: get_keyword_documentation() takes exactly 3 arguments (2 given)
[ ERROR ] Adding keyword 'No Arg Spec' to library 'classes.InvalidGetDocDynamicLibrary' failed: Calling dynamic method 'get_keyword_documentation' failed: TypeError: get_keyword_documentation() takes exactly 3 arguments (2 given)
[ ERROR ] Adding keyword 'One Arg' to library 'classes.InvalidGetDocDynamicLibrary' failed: Calling dynamic method 'get_keyword_documentation' failed: TypeError: get_keyword_documentation() takes exactly 3 arguments (2 given)
[ ERROR ] Adding keyword 'One or Two Args' to library 'classes.InvalidGetDocDynamicLibrary' failed: Calling dynamic method 'get_keyword_documentation' failed: TypeError: get_keyword_documentation() takes exactly 3 arguments (2 given)
```

and this:

```
======================================================================
FAIL: test_custom_stdout (test_run_and_rebot.TestRebot)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philipp/repos/robotframework/utest/api/test_run_and_rebot.py", line 176, in test_custom_stdout
    self._assert_outputs()
  File "/home/philipp/repos/robotframework/utest/resources/runningtestcase.py", line 40, in _assert_outputs
    self._assert_output(sys.__stderr__, stderr)
  File "/home/philipp/repos/robotframework/utest/resources/runningtestcase.py", line 50, in _assert_output
    self._assert_no_output(output)
  File "/home/philipp/repos/robotframework/utest/resources/runningtestcase.py", line 54, in _assert_no_output
    raise AssertionError('Expected output to be empty:
%s' % output)
AssertionError: Expected output to be empty:
[ ERROR ] Error in file '/home/philipp/repos/robotframework/atest/testdata/misc/warnings_and_errors.robot': Non-existing setting 'Non-Existing'.
```

**Comment by philsc** [comment]
This is with current master (667dfb9) and Python 2.7.9 on Debian Jessie.

**Comment by pekkaklarck** [comment]
I assume this is related to Robot's automatic internal logging. Most likely it is disable by some tests and subsequent tests also expect it to be disabled. I've haven't bothered to study this more deeply because the whole internal logging system should actually be rewritten. Ideas how to enhance the current situation in form of PRs or otherwise are appreciated, though.

**Comment by philsc** [comment]
Your assessment sounds reasonable. Unfortunately, I don't understand how the internal logging works well enough to tackle this with the time I've got allocated for this.

I ended up applying the following patch to work around this issue:
```patch
diff --git a/utest/run.py b/utest/run.py
index e501942..59bb120 100755
--- a/utest/run.py
+++ b/utest/run.py
@@ -34,7 +34,7 @@ def get_tests(directory=None):
         directory = base
     sys.path.insert(0, directory)
     tests = []
-    for name in os.listdir(directory):
+    for name in sorted(os.listdir(directory)):
         if name.startswith("."): continue
         fullname = os.path.join(directory, name)
         if os.path.isdir(fullname):
```

**Comment by pekkaklarck** [comment]
I thought os.listdir returns items in sorted order but apparently not. I agree this is a good enough workaround.
