### ISSUE TITLE
Attribute ERROR while launching ride.py

### ISSUE THREAD

**Issue by mgr390** [robotframework/robotframework#2341]
Hello,

How can i fix this problem? Ride.py fails while launching it

mgr-pc:.ssh mgr$ ride.py
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotide/__init__.py", line 73, in main
    _run(inpath, not noupdatecheck, debug_console)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotide/__init__.py", line 99, in _run
    ride = RIDE(inpath, updatecheck)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotide/application/application.py", line 42, in __init__
    wx.App.__init__(self, redirect=False)
  File "/usr/local/lib/python2.7/site-packages/wx-2.9.5-osx_cocoa/wx/_core.py", line 8631, in __init__
    self._BootstrapApp()
  File "/usr/local/lib/python2.7/site-packages/wx-2.9.5-osx_cocoa/wx/_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotide/application/application.py", line 59, in OnInit
    self.frame.tree.populate(self.model)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotide/ui/tree.py", line 211, in populate
    self._populate_model(model)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotide/ui/tree.py", line 230, in _populate_model
    self._render_datafile(self._root, model.data, 0)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotide/ui/tree.py", line 277, in _render_datafile
    self._render_datafile(node, child)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotide/ui/tree.py", line 270, in _render_datafile
    node = self._create_node_with_handler(parent_node, controller, index)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/robotide/ui/tree.py", line 286, in _create_node_with_handler
    self.SetItemTextColour(node, wx.ColorRGB(0xA9A9A9))
AttributeError: 'module' object has no attribute 'ColorRGB'

**Comment by HelioGuilherme66** [comment]
This Issue does not belong in this github project. You should open in [RIDE](https://github.com/robotframework/RIDE).
I see that you are using MacOS, please add that version to the new Issue. What version of RIDE is that? The error you found was already detected and has to deal with the wxPython version (2.9.5).

**Comment by pekkaklarck** [comment]
Wrong tracker.
