### ISSUE TITLE
Python 3.5.2 not expecting str

### ISSUE THREAD

**Issue by rlucca** [robotframework/robotframework#2543]
When I try run the acceptance test, I get an exception. I'm using python 3.5.2. If I change back to python 2.7, it is fine.

```
Traceback (most recent call last):
  File "atest/run.py", line 134, in <module>
    rc = atests(*sys.argv[1:])
  File "atest/run.py", line 72, in atests
    interpreter = InterpreterFactory(interpreter)
  File "/home/rlucca/Git/robotframework/atest/interpreter.py", line 18, in InterpreterFactory
    return Interpreter(path, name, version)
  File "/home/rlucca/Git/robotframework/atest/interpreter.py", line 27, in __init__
    name, version = self._get_name_and_version()
  File "/home/rlucca/Git/robotframework/atest/interpreter.py", line 41, in _get_name_and_version
    name = name if 'PyPy' not in output else 'PyPy'
TypeError: a bytes-like object is required, not 'str'
```

**Comment by pekkaklarck** [comment]
Acceptance test system itself isn't Python 3 compatible. You need to run `atest/run.py` using Python 2.7. `atest/README.rst` ought to explain this. This limitation could obviously be lifted.
