### ISSUE TITLE
robot.errors.DataError: Reading XML source failed: ParseError: no element found

### ISSUE THREAD

**Issue by banrieen** [robotframework/robotframework#2547]
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main
PabotLib process stopped
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\lib\site-packages\pabot\pabot.py", line 643, in <module>
    main(sys.argv[1:])
  File "C:\Python27\lib\site-packages\pabot\pabot.py", line 630, in main
    _get_suite_root_name(suite_names)))
  File "C:\Python27\lib\site-packages\pabot\pabot.py", line 505, in _report_results
    return _report_results_for_one_run(outs_dir, options, start_time_string, tests_root_name)
  File "C:\Python27\lib\site-packages\pabot\pabot.py", line 509, in _report_results_for_one_run
    output_path = _merge_one_run(outs_dir, options, tests_root_name)
  File "C:\Python27\lib\site-packages\pabot\pabot.py", line 532, in _merge_one_run
    merge(files, options, tests_root_name).save(output_path)
  File "C:\Python27\lib\site-packages\pabot\result_merger.py", line 131, in merge
    settings.non_critical_tags, tests_root_name)
  File "C:\Python27\lib\site-packages\pabot\result_merger.py", line 118, in merge_groups
    non_critical_tags).values():
  File "C:\Python27\lib\site-packages\pabot\result_merger.py", line 109, in group_by_root
    res = ExecutionResult(src)
  File "C:\Python27\lib\site-packages\robot\result\resultbuilder.py", line 46, in ExecutionResult
    return _single_result(sources[0], options)
  File "C:\Python27\lib\site-packages\robot\result\resultbuilder.py", line 70, in _single_result
    raise DataError("Reading XML source '%s' failed: %s" % (unic(ets), error))
robot.errors.DataError: Reading XML source 'E:\autotest\autotest2.0\output\20170216_120910_test_std_5GAPMode.ini_10__5GAPMode_11an\pabot_results\autotest.3 Wireless.4 5G APMode.6 1 11Na Connectivity.6 1 11Na Connectivity Open Long Wep Index2 A2C\output.xml' failed: ParseError: no element found: line 195320, column 47

**Comment by pekkaklarck** [comment]
Seems to happen when using Pabot. If you report the issue there, please provide more information about how you used the tool. Just giving a traceback isn't typically enough for others to understand what's going on. If you are certain the problem is in Robot, not Pabot, please provide more information about it here.
