### ISSUE TITLE
Unexpected termination when multiple failures in robot framework

### ISSUE THREAD

**Issue by spire-29** [robotframework/robotframework#2615]
Robot Framework Version: 3.02

I have configured my exception class as:

{..
public final static boolean ROBOT_CONTINUE_ON_FAILURE = true;
..}

After i upgraded to Rf 3.02, if a test raises multiple failures, then robotframework exits with the below error:

[ ERROR ] Unexpected error: TypeError: enumerate() takes at most 1 arguments (2 given)
Traceback (most recent call last):
  File "C:\jython2.7b1\Lib\site-packages\robot\utils\application.py", line 83, in _execute
    rc = self.main(arguments, **options)
  File "C:\jython2.7b1\Lib\site-packages\robot\run.py", line 445, in main
    result = suite.run(settings)
  File "C:\jython2.7b1\Lib\site-packages\robot\running\model.py", line 248, in run
    self.visit(runner)
  File "C:\jython2.7b1\Lib\site-packages\robot\model\testsuite.py", line 161, in visit
    visitor.visit_suite(self)
  File "C:\jython2.7b1\Lib\site-packages\robot\model\visitor.py", line 86, in visit_suite
    suite.suites.visit(self)
  File "C:\jython2.7b1\Lib\site-packages\robot\model\itemlist.py", line 76, in visit
    item.visit(visitor)
  File "C:\jython2.7b1\Lib\site-packages\robot\model\testsuite.py", line 161, in visit
    visitor.visit_suite(self)
  File "C:\jython2.7b1\Lib\site-packages\robot\model\visitor.py", line 86, in visit_suite
    suite.suites.visit(self)
  File "C:\jython2.7b1\Lib\site-packages\robot\model\itemlist.py", line 76, in visit
    item.visit(visitor)
  File "C:\jython2.7b1\Lib\site-packages\robot\model\testsuite.py", line 161, in visit
    visitor.visit_suite(self)
  File "C:\jython2.7b1\Lib\site-packages\robot\model\visitor.py", line 86, in visit_suite
    suite.suites.visit(self)
  File "C:\jython2.7b1\Lib\site-packages\robot\model\itemlist.py", line 76, in visit
    item.visit(visitor)
  File "C:\jython2.7b1\Lib\site-packages\robot\model\testsuite.py", line 161, in visit
    visitor.visit_suite(self)
  File "C:\jython2.7b1\Lib\site-packages\robot\model\visitor.py", line 86, in visit_suite
    suite.suites.visit(self)
  File "C:\jython2.7b1\Lib\site-packages\robot\model\itemlist.py", line 76, in visit
    item.visit(visitor)
  File "C:\jython2.7b1\Lib\site-packages\robot\model\testsuite.py", line 161, in visit
    visitor.visit_suite(self)
  File "C:\jython2.7b1\Lib\site-packages\robot\model\visitor.py", line 87, in visit_suite
    suite.tests.visit(self)
  File "C:\jython2.7b1\Lib\site-packages\robot\model\itemlist.py", line 76, in visit
    item.visit(visitor)
  File "C:\jython2.7b1\Lib\site-packages\robot\model\testcase.py", line 74, in visit
    visitor.visit_test(self)
  File "C:\jython2.7b1\Lib\site-packages\robot\running\runner.py", line 134, in visit_test
    StepRunner(self._context,
  File "C:\jython2.7b1\Lib\site-packages\robot\running\runner.py", line 134, in visit_test
    StepRunner(self._context,
  File "C:\jython2.7b1\Lib\site-packages\robot\running\steprunner.py", line 47, in run_steps
    raise ExecutionFailures(errors)
  File "C:\jython2.7b1\Lib\site-packages\robot\errors.py", line 177, in __init__
    message = message or self._format_message([e.message for e in errors])
  File "C:\jython2.7b1\Lib\site-packages\robot\errors.py", line 190, in _format_message
    ['%d) %s' % (i, m) for i, m in enumerate(messages, start=1)]

**Comment by pekkaklarck** [comment]
Python's `enumerate` function certainly takes two arguments with Python/Jython > 2.5. It could be that Jython 2.7 beta 1 that you seem to be using still doesn't support it and I'd try upgrading it first.

**Comment by pekkaklarck** [comment]
No new info since last summer. Closing.
