### ISSUE TITLE
How to download images using robot framework

### ISSUE THREAD

**Issue by dipakbachhav** [robotframework/robotframework#2694]
Hi ,

I am trying to download image using robot framework & xpath  but no luck yet. Can someone please provide me code to download images on my local machine.

Regards,
Dipak

**Comment by gsumano** [comment]
Use AutoIt library

**Comment by dipakbachhav** [comment]
Hi,
I am getting issue with autoit library. Can you please check and let me know `your` valuable thoughts. 
```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Python27\Lib\site-packages\AutoItLibrary\lib>regsvr32  AutoItX3.dll

C:\Python27\Lib\site-packages\AutoItLibrary\lib>cd ../../../

C:\Python27\Lib>cd ../Scripts

C:\Python27\Scripts>>pip install robotframework-autoitlibrary
'install' is not recognized as an internal or external command,
operable program or batch file.

C:\Python27\Scripts>pip install robotframework-autoitlibrary
Collecting robotframework-autoitlibrary
  Using cached robotframework-autoitlibrary-1.1.zip
Installing collected packages: robotframework-autoitlibrary
  Running setup.py install for robotframework-autoitlibrary ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools
, tokenize;__file__='c:\\users\\duser\\appdata\\local\\temp\\pip-build-xvc
14c\\robotframework-autoitlibrary\\setup.py';f=getattr(tokenize, 'open', open)(_
_file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file
__, 'exec'))" install --record c:\users\duser\appdata\local\temp\pip-tbp8s
c-record\install-record.txt --single-version-externally-managed --compile:
    Don't think we need to unregister the old one...
    %SYSTEMROOT%\system32\regsvr32.exe /S c:\python27\Lib\site-packages\AutoItLi
brary\lib\AutoItX3.dll
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\duser\appdata\local\temp\pip-build-xvc14c\robotframew
ork-autoitlibrary\setup.py", line 70, in <module>
        subprocess.check_call(cmd, shell=True)
      File "c:\python27\lib\subprocess.py", line 540, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '%SYSTEMROOT%\system32\regsvr32.exe /
S c:\python27\Lib\site-packages\AutoItLibrary\lib\AutoItX3.dll' returned non-zer
o exit status 5

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\duser\\appdata\\local\\temp\\pip-build-xvc14c\\robotframework-auto
itlibrary\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --
record c:\users\duser\appdata\local\temp\pip-tbp8sc-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c
:\users\duser\appdata\local\temp\pip-build-xvc14c\robotframework-autoitlibrary\

C:\Python27\Scripts>
```

**Comment by pekkaklarck** [comment]
This issue tracker is for bug reports and enhancement requests related to Robot Framework itself. The framework doesn't have built-in capabilities for downloading anything and I believe such functionality is best kept in generic or custom libraries outside the core.

For support you can use, for example, mailing lists or Slack. If you don't get reply, you should think is there possibly something wrong in your question or how you phrase it. People on these support forums are not paid and you cannot expect to get good answers to vague questions. If you are unsure how to ask smart questions, you may want to take a look at this classic article about exactly that topic: http://www.catb.org/esr/faqs/smart-questions.html
