### ISSUE TITLE
Import Library HITH NAME does not work properly when importing multiple libraries with the same file name

### ISSUE THREAD

**Issue by szymonslodkowski** [robotframework/robotframework#2718]
I am using Robot Framework 3.0.3 and Python 2.7.
In tests I am using several libraries (the same filename in different subdirs) and I would like to import these libraries dynamically, but there is an error.

Small workspace to reproduce issue is attached
[import_problem.zip](https://github.com/robotframework/robotframework/files/1482481/import_problem.zip)

Log:
```
Command: /usr/bin/python -m robot.run --listener /tmp/RobotTempDir5575380268093330458/TestRunnerAgent.py:37136 --argumentfile /tmp/RobotTempDir5575380268093330458/args_3091e758.arg /home/szsl/workspace/import_problem
Suite Executor: Robot Framework 3.0.3.dev20170213 (Python 2.7.12 on linux2)
==============================================================================
Import Problem                                                                
==============================================================================
Import Problem.Tests                                                          
==============================================================================
test1                                                                 | PASS |
------------------------------------------------------------------------------
test2                                                                 | FAIL |
Initializing test library 'cs1' with no arguments failed: TypeError: super() argument 1 must be type, not None
Traceback (most recent call last):
  File "/home/szsl/workspace/import_problem/custom_setup_1/custom_setup.py", line 7, in __init__
    super(custom_setup, self).__init__()
------------------------------------------------------------------------------
test3                                                                 | FAIL |
Initializing test library 'test3_cs1' with no arguments failed: TypeError: super() argument 1 must be type, not None
Traceback (most recent call last):
  File "/home/szsl/workspace/import_problem/custom_setup_1/custom_setup.py", line 7, in __init__
    super(custom_setup, self).__init__()
------------------------------------------------------------------------------
test4                                                                 | FAIL |
Initializing test library 'test4_cs1' with no arguments failed: TypeError: super() argument 1 must be type, not None
Traceback (most recent call last):
  File "/home/szsl/workspace/import_problem/custom_setup_1/custom_setup.py", line 7, in __init__
    super(custom_setup, self).__init__()
------------------------------------------------------------------------------
Import Problem.Tests                                                  | FAIL |
4 critical tests, 1 passed, 3 failed
4 tests total, 1 passed, 3 failed
==============================================================================
Import Problem                                                        | FAIL |
4 critical tests, 1 passed, 3 failed
4 tests total, 1 passed, 3 failed
==============================================================================
Output:  /home/szsl/workspace/import_problem/output.xml
Log:     /home/szsl/workspace/import_problem/log.html
Report:  /home/szsl/workspace/import_problem/report.html
```

Please note that when ONLY this
```
test4
    import library    /home/szsl/workspace/import_problem/custom_setup_1/custom_setup.py    WITH NAME    test4_cs1
    ${lib1_object} =    get library instance    test4_cs1
    Call method    ${lib1_object}    my_keyword
    import library    /home/szsl/workspace/import_problem/custom_setup_2/custom_setup.py    WITH NAME    test4_cs2
    ${lib2_object} =    get library instance    test4_cs2
    Call method    ${lib2_object}    my_keyword
    Call method    ${lib1_object}    my_keyword
```
 is executed error is in LAST LINE and is different:
```
Suite Executor: Robot Framework 3.0.3.dev20170213 (Python 2.7.12 on linux2)
==============================================================================
Import Problem                                                                
==============================================================================
Import Problem.Tests                                                          
==============================================================================
test4                                                                 | FAIL |
Calling method 'my_keyword' failed: AttributeError: 'NoneType' object has no attribute 'info'
------------------------------------------------------------------------------
Import Problem.Tests                                                  | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Import Problem                                                        | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
```

**Comment by pekkaklarck** [comment]
My guess is that this is due to Robot removing earlier imported module from `sys.modules` to be able to import a new module with same name. This makes the old module unusable. I don't think anything can really be done to it because there can only be one module with same name in `sys.modules`. I would recommend not using library with same name at least in same test.

**Comment by szymonslodkowski** [comment]
In my real environment one test is using one library imported dynamically and problem occurs when given tests needs to use library already used by previous tests (but not last one).
I have implemented workaround for this:

```
    def get_object_from_custom_library(source_path, module_name, class_name, *args, **kwargs):
        imported_module = imp.load_source(module_name, source_path)
        object_to_return = getattr(imported_module, class_name)(*args, **kwargs)
        return object_to_return
```

and this works perfectly

**Comment by pekkaklarck** [comment]
Interesting. Can you look could `imp.load_source` be used in Robot's code as well? We currently just use `__import__`. The main problem with changing this logic is that it needs to work with all supported interpreters (Python 2 and 3, Jython, IronPython, PyPy 2 and 3).

**Comment by szymon-slodkowski** [comment]
@pekkaklarck Sorry for answering with big delay. Some time ago I spent some time on this issue. And I am able to reproduce problem only with python2. I have checked also with ironpython and python3 and works without problem (I didn't check Jython). Franky I am not sure if it make sense to change import mechanism in that case. What do you think?

**Comment by szymonslodkowski** [comment]
@pekkaklarck Sorry for answering with big delay. Some time ago I spent some time on this issue. And I am able to reproduce problem only with python2. I have checked also with ironpython and python3 and works without problem (I didn't check Jython). Franky I am not sure if it make sense to change import mechanism in that case. What do you think?

**Comment by pekkaklarck** [comment]
Does it make sense to fix this depends mainly on how complicated the fix would be and can reliable acceptance tests be created for it. Now before RF 3.1 it would be a great time.

**Comment by pekkaklarck** [comment]
This could be related to #2106.
