### ISSUE TITLE
Robot framework Ironpython issue importError: No module named expat; use SimpleXMLTreeBuilder instead

### ISSUE THREAD

**Issue by rkommine** [robotframework/robotframework#2723]
Hi,

I am working on Robot framework with ironpython. I have installed Iron python 2.7.7 & installed robotframework.

```
C:\Users\rkommine\Downloads\robotframework-master>ipybot --version
Robot Framework 3.0.3.dev20170213 (IronPython 2.7.7 on cli)
```

After this I have written a simple class library Visual Studo. NET

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ClassLibrary3
{
    public class Class1
    {
        public int AddNumbers(int num1,int num2)
        {
            return num1 + num2;
        }
    }
}
```
Compiled this into a DLL file.

```
1>------ Build started: Project: ClassLibrary3, Configuration: Debug Any CPU ------
1>  ClassLibrary3 -> C:\Workspace\VISUAL_STUDIO\CSHARP\ClassLibrary3\ClassLibrary3\bin\Debug\ClassLibrary3.dll
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```
Now I created a ironpython script CombineLibrary & imported this DLL

```
import clr

clr.AddReferenceToFileAndPath("C:\\Workspace\\RobotFramework\\IronPython\\ClassLibrary3.dll")
import ClassLibrary3

def add_Numbers(num1,num2):
	cmb = Class1()
	total = cmb.AddNumbers(int(num1),int(num2))
	return total
```
I have imported this python script as a library into my robot framework test suite. When I execute the Testsuite using ipybot I am getting below issue:

```
C:\Workspace\RobotFramework\IronPython>ipybot Testsuite1.robot
==============================================================================
Testsuite1
==============================================================================
TC1                                                                   | FAIL |
NameError: global name 'Class1' is not defined
------------------------------------------------------------------------------
Testsuite1                                                            | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  C:\Workspace\RobotFramework\IronPython\output.xml
[ ERROR ] Reading XML source 'C:\Workspace\RobotFramework\IronPython\output.xml' failed: ImportError: No module named expat; use SimpleXMLTreeBuilder instead

Try --help for usage information.

C:\Workspace\RobotFramework\IronPython>
```
Could you please help to fix the issue?
I have attached the complete folder containing ironpython script, robotframework testsuite & the dll file.
[IronPython.zip](https://github.com/robotframework/robotframework/files/1510992/IronPython.zip)

Thanks in advance.

**Comment by pekkaklarck** [comment]
That `NameError` seems to be a bug in your code. You are using `Class1` but have only imported `ClassLibrary3`.

Did you install the external ElementTree module as instructed by the [installation instructions](https://github.com/robotframework/robotframework/blob/master/INSTALL.rst#ironpython-installation)?

**Comment by rkommine** [comment]
Hi,

Many thanks for the response. After no of tries I was able to make it work by adding the line "from ClassLibrary3 import Class1" to CombineLibrary.py file.

```
import clr
import sys

clr.AddReferenceToFileAndPath("C:\\Workspace\\RobotFramework\\IronPython\\ClassLibrary3.dll")
from ClassLibrary3 import Class1

def add_Numbers(num1,num2):
    cmb = Class1()
    total = cmb.AddNumbers(int(num1),int(num2))
    print total

```
But still I am getting below error.

```
rkommine@N-5CG4483H2K C:\Workspace\RobotFramework\IronPython
> ipybot Testsuite1.robot
==============================================================================
Testsuite1
==============================================================================
TC1                                                                   | PASS |
------------------------------------------------------------------------------
Testsuite1                                                            | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
Output:  C:\Workspace\RobotFramework\IronPython\output.xml
[ ERROR ] Reading XML source 'C:\Workspace\RobotFramework\IronPython\output.xml' failed: ImportError: No module named expat; use SimpleXMLTreeBuilder instead

Try --help for usage information.
```
I have installed elementtree on top of ironpython

```
rkommine@N-5CG4483H2K C:\Workspace\RobotFramework\IronPython
> ipy
IronPython 2.7.7 (2.7.7.0) on .NET 4.0.30319.42000 (32-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>> import elementtree
>>>
```

Also I have tried installing the expat module for which error was showing using pip install. But I am getting below error:

```
rkommine@N-5CG4483H2K C:\Workspace\RobotFramework\IronPython
> ipy -X:Frames -m pip install expat
Unhandled exception:
Traceback (most recent call last):
  File "C:\Tools\IronPython27\Lib\runpy.py", line 182, in run_module
  File "C:\Tools\IronPython27\Lib\site-packages\pip\_vendor\pyparsing.py", line 1261, in setParseAction
  File "C:\Tools\IronPython27\Lib\site-packages\pip\_vendor\pyparsing.py", line 1043, in _trim_arity
  File "C:\Tools\IronPython27\Lib\runpy.py", line 111, in _get_module_details
  File "C:\Tools\IronPython27\Lib\site-packages\pip\__init__.py", line 26, in <module>
  File "C:\Tools\IronPython27\Lib\site-packages\pip\utils\__init__.py", line 27, in <module>
  File "C:\Tools\IronPython27\Lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 74, in <module>
  File "C:\Tools\IronPython27\Lib\site-packages\pip\_vendor\packaging\requirements.py", line 9, in <module>
  File "C:\Tools\IronPython27\Lib\site-packages\pip\_vendor\pyparsing.py", line 4715, in <module>
IndexError: index out of range: -1

```

**Comment by pekkaklarck** [comment]
1. You need to install a special version of ElementTree. All this is explained in Robot Framework's installation instructions I linked in my previous comment.

2. The problem with pip not working with IronPython is a bug in IronPython itself. You cannot install the aforementioned ElementTree version with pip anyway.

**Comment by rkommine** [comment]
Many thanks for the hint. By mistake instead of installing  elementtree-1.2.7-20070827-preview.zip I have installed elementtree-1.2.6-20050316.zip. 

Now after installing preview release elementtree-1.2.7-20070827-preview.zip it is working fine.
```
> ipybot Testsuite1.robot
==============================================================================
Testsuite1
==============================================================================
TC1                                                                   | PASS |
------------------------------------------------------------------------------
Testsuite1                                                            | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
Output:  C:\Workspace\RobotFramework\IronPython\output.xml
Log:     C:\Workspace\RobotFramework\IronPython\log.html
Report:  C:\Workspace\RobotFramework\IronPython\report.html
```
