### ISSUE TITLE
Issue with building standalone robotframework jar from source

### ISSUE THREAD

**Issue by mdiwakar** [robotframework/robotframework#2873]
- clone the repository and checked out out master branch on Windows 10 and Mac OSX

- installed requirements   " pip install -r requirements-build.txt"

- execute "invoke  jar"

got the following error

c:\robotframework>invoke --list
Traceback (most recent call last):
  File "c:\Python27\Scripts\invoke-script.py", line 11, in <module>
    load_entry_point('invoke', 'console_scripts', 'invoke')()
  File "c:\robotframework\src\invoke\invoke\program.py", line 321, in run
    self.parse_collection()
  File "c:\robotframework\src\invoke\invoke\program.py", line 399, in parse_collection
    self.load_collection()
  File "c:\robotframework\src\invoke\invoke\program.py", line 588, in load_collection
    module, parent = loader.load(coll_name)
  File "c:\robotframework\src\invoke\invoke\loader.py", line 77, in load
    module = imp.load_module(name, fd, path, desc)
  File "c:\robotframework\tasks.py", line 124
    raise Exit(f"'{name}' is not a unique library prefix.")
                                                         ^
SyntaxError: invalid syntax

c:\robotframework>

**Comment by pekkaklarck** [comment]
You need to use Python 3.6 or newer. See BUILD.rst for details.
