### ISSUE TITLE
JAR package: 'ImportError: cannot import name setitimer'

### ISSUE THREAD

**Issue by dnekhayev** [robotframework/robotframework#3050]
Getting 'ImportError: cannot import name setitimer' error while running the JAR package.
The error doesn't occur in Robot Framework 3.1 beta 1
OS: openSUSE
Exception in thread "MainThread" Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "robotframework-3.1.1.jar/Lib/robot/__init__$py.class", line 44, in <module>
  File "robotframework-3.1.1.jar/Lib/robot/rebot$py.class", line 45, in <module>
  File "robotframework-3.1.1.jar/Lib/robot/run$py.class", line 44, in <module>
  File "robotframework-3.1.1.jar/Lib/robot/running/__init__$py.class", line 103, in <module>
  File "robotframework-3.1.1.jar/Lib/robot/running/userkeyword$py.class", line 25, in <module>
  File "robotframework-3.1.1.jar/Lib/robot/running/userkeywordrunner$py.class", line 29, in <module>
  File "robotframework-3.1.1.jar/Lib/robot/running/timeouts/__init__$py.class", line 29, in <module>
  File "robotframework-3.1.1.jar/Lib/robot/running/timeouts/posix$py.class", line 16, in <module>

**Comment by pekkaklarck** [comment]
Which version does the problem occur? How did you use the jar distribution?

**Comment by dnekhayev** [comment]
The problem has occurred since RF 3.1 RC1 (one of commits between 3.1B1 and 3.1RC1).
Since I use Java, RF JAR distribution is used as a part of an autotest distribution.

**Comment by pekkaklarck** [comment]
Can you provide an example how to reproduce the problem?

**Comment by dnekhayev** [comment]
invoke jar
java -jar dist/robotframework-3.1rc1.jar

**Comment by pekkaklarck** [comment]
Where did you get that jar? They weren't created with pre-releases. With the final release I tested the released jar and it worked fine.

**Comment by dnekhayev** [comment]
Hmm...
Here might be the problem:
$ java --version
openjdk 12-internal 2019-03-19
OpenJDK Runtime Environment (build 12-internal+16-suse-1.1-x8664)
OpenJDK 64-Bit Server VM (build 12-internal+16-suse-1.1-x8664, mixed mode)

java on my machine has been switched to OpenJDK unexpectedly

**Comment by dnekhayev** [comment]
It works good with oracle java 11.0.1
This is a configuration issue.
Closing the issue since it's not a bug.

**Comment by danielleberre** [comment]
I am experiencing the exact same issue with RF 3.2.2 jar distribution on a macOS 11.1 running either 

Oracle Java 11

```
java version "11" 2018-09-25
Java(TM) SE Runtime Environment 18.9 (build 11+28)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11+28, mixed mode)
```

or OpenJDK 15

```
openjdk version "15" 2020-09-15
OpenJDK Runtime Environment AdoptOpenJDK (build 15+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15+36, mixed mode, sharing)
```

while it works fine java Oracle Java 8

```
java version "1.8.0"
Java(TM) SE Runtime Environment (build 1.8.0-b132)
Java HotSpot(TM) 64-Bit Server VM (build 25.0-b70, mixed mode)
```

**Comment by pekkaklarck** [comment]
This was a bug after all. See #4100 for details.
