### ISSUE TITLE
RIDE-1.5.2.1 can not import all the base Libraries,the RIDE log :table libraries has 5 columns but 4 values were supplied

### ISSUE THREAD

**Issue by tangxingjun** [robotframework/robotframework#3067]
the error log :20190124 16:29:46.002 [WARN]: Library import handling threw an unexpected exception

Traceback (most recent call last):
table libraries has 5 columns but 4 values were supplied
  File "C:\Python27\lib\site-packages\robotide\spec\librarymanager.py", line 40, in run
    if not self._handle_message():
  File "C:\Python27\lib\site-packages\robotide\spec\librarymanager.py", line 66, in _handle_message
    self._handle_insert_keywords_message(message)
  File "C:\Python27\lib\site-packages\robotide\spec\librarymanager.py", line 95, in _handle_insert_keywords_message
    lambda res: result_queue.put(res, timeout=3))
  File "C:\Python27\lib\site-packages\robotide\spec\librarymanager.py", line 99, in _insert
    library_name, library_args, keywords or [])
  File "C:\Python27\lib\site-packages\robotide\spec\librarydatabase.py", line 84, in insert_library_keywords
    lib = self._insert_library(library_name, library_arguments, cur)
  File "C:\Python27\lib\site-packages\robotide\spec\librarydatabase.py", line 111, in _insert_library
    cursor.execute('insert into libraries values (null, ?, ?, ?)', (name, unicode(arguments), time.time()))

**Comment by aaltat** [comment]
The exception is raised by RIDE, which is an test data editor/IDE for Robot Framework. It would be best to report the problem in RIDE issue tracker https://github.com/robotframework/RIDE

**Comment by pekkaklarck** [comment]
Tatu is right. The problem seems to be in RIDE.

**Comment by tangxingjun** [comment]
solution:
when more than 2 version of robotframe-ride on localhost:
we need delete the file: librarykeywords.db with path: C:\Users\Administrator\AppData\Roaming\RobotFramework\ride.
