### ISSUE TITLE
Libdoc, TestDoc and Tidy crash if output file is invalid

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#3339]
All the tools mentioned in the title fail like this if their output file cannot be opened:

```
$ python -m robot.libdoc BuiltIn out.html
Unexpected error: IOError: [Errno 13] Permission denied: 'out.html'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/robot/utils/application.py", line 83, in _execute
    rc = self.main(arguments, **options)
  File "/usr/local/lib/python2.7/dist-packages/robot/libdoc.py", line 158, in main
    libdoc.save(output, self._get_output_format(format, output))
  File "/usr/local/lib/python2.7/dist-packages/robot/libdocpkg/model.py", line 52, in save
    with LibdocOutput(output, format) as outfile:
  File "/usr/local/lib/python2.7/dist-packages/robot/libdocpkg/output.py", line 30, in __enter__
    self._output_file = file_writer(self._output_path)
  File "/usr/local/lib/python2.7/dist-packages/robot/utils/robotio.py", line 23, in file_writer
    f = io.open(path, 'w', encoding=encoding, newline=newline)
```

This is an error situation so failing is OK, but failures shown to users should never look like the above. This is to some extend related to #2767 about these tools not creating output file directories automatically.

**Comment by pekkaklarck** [comment]
This is now fixed with Libdoc and Testdoc. Tidy fixes need to wait until Tidy is fixed in general after the new parser broke it.
