### ISSUE TITLE
CI: Jython 2.7.2rc1 + Java >= 9 - failures of few unit tests

### ISSUE THREAD

**Issue by tysonite** [robotframework/robotframework#3495]
Starting from v2.7.2rc1, Jython supports Java 11. There are few failures of unit tests on CI in such combination on Macos, Linux and Win, the same tests pass on Jython 2.7.2rc1 + Java8. :
```
======================================================================
FAIL: test_original_signal_handlers_are_restored (test_run_and_rebot.TestSignalHandlers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/robotframework/robotframework/utest/api/test_run_and_rebot.py", line 317, in test_original_signal_handlers_are_restored
    assert_equal(signal.getsignal(signal.SIGINT), orig_sigint)
  File "/home/runner/work/robotframework/robotframework/utest/../src/robot/utils/asserts.py", line 182, in assert_equal
    _report_inequality(first, second, '!=', msg, values, formatter)
  File "/home/runner/work/robotframework/robotframework/utest/../src/robot/utils/asserts.py", line 231, in _report_inequality
    raise AssertionError(msg)
AssertionError: java.lang.Terminator$1@30722243 (Signal$SunMiscHandler) != java.lang.Terminator$1@30722243 (Signal$SunMiscHandler)

======================================================================
FAIL: test_original_signal_handlers_are_restored (test_running.TestPreservingSignalHandlers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/robotframework/robotframework/utest/running/test_running.py", line 249, in test_original_signal_handlers_are_restored
    assert_equal(signal.getsignal(signal.SIGINT), self.orig_sigint)
  File "/home/runner/work/robotframework/robotframework/utest/../src/robot/utils/asserts.py", line 182, in assert_equal
    _report_inequality(first, second, '!=', msg, values, formatter)
  File "/home/runner/work/robotframework/robotframework/utest/../src/robot/utils/asserts.py", line 231, in _report_inequality
    raise AssertionError(msg)
AssertionError: java.lang.Terminator$1@30722243 (Signal$SunMiscHandler) != java.lang.Terminator$1@30722243 (Signal$SunMiscHandler)

======================================================================
FAIL: test_restore_when_failure (test_signalhandler.TestRestoringOriginalHandlers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/robotframework/robotframework/utest/running/test_signalhandler.py", line 110, in test_restore_when_failure
    assert_equal(self.get_int(), self.orig_int)
  File "/home/runner/work/robotframework/robotframework/utest/../src/robot/utils/asserts.py", line 182, in assert_equal
    _report_inequality(first, second, '!=', msg, values, formatter)
  File "/home/runner/work/robotframework/robotframework/utest/../src/robot/utils/asserts.py", line 231, in _report_inequality
    raise AssertionError(msg)
AssertionError: java.lang.Terminator$1@30722243 (Signal$SunMiscHandler) != java.lang.Terminator$1@30722243 (Signal$SunMiscHandler)

======================================================================
FAIL: test_restore_when_no_failures (test_signalhandler.TestRestoringOriginalHandlers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/robotframework/robotframework/utest/running/test_signalhandler.py", line 97, in test_restore_when_no_failures
    assert_equal(self.get_int(), self.orig_int)
  File "/home/runner/work/robotframework/robotframework/utest/../src/robot/utils/asserts.py", line 182, in assert_equal
    _report_inequality(first, second, '!=', msg, values, formatter)
  File "/home/runner/work/robotframework/robotframework/utest/../src/robot/utils/asserts.py", line 231, in _report_inequality
    raise AssertionError(msg)
AssertionError: java.lang.Terminator$1@30722243 (Signal$SunMiscHandler) != java.lang.Terminator$1@30722243 (Signal$SunMiscHandler)

----------------------------------------------------------------------
```

For example, refer to [this](https://github.com/tysonite/robotframework/runs/491363274?check_suite_focus=true#step:6:1659) run.

**Comment by pekkaklarck** [comment]
These errors look really strange but luckily seem to have the same root cause. Unfortunately I only have Java 8 installed at the moment so cannot test this locally, but hopefully someone else can debug this a bit.

All these tests seem to be doing something like this:

```python
original_sigint_handler = signal.getsignal(signal.SIGINT)
# do something that sets sigint handler but should at the end reset the original
current_sigint_handler = signal.getsignal(signal.SIGINT)
assert original_sigint_handler == current_sigint_handler
```

It's first of all strange these tests fail, but it is even more strange based on the error message at least the string representation of the original and current handlers are exactly same.

**Comment by pekkaklarck** [comment]
Are these errors already resolved?

**Comment by pekkaklarck** [comment]
These tests are now passing, right? If not, we can continue discussion on Slack.
