### ISSUE TITLE
Robot Framework and websockets integration results a RuntimeError exception

### ISSUE THREAD

**Issue by danashevskiy** [robotframework/robotframework#3581]
I need to use `websockets` lib for test creation with the help of Robot Framework application. The issue is during test execution, I receive `[ ERROR ] Task was destroyed but it is pending!`, `RuntimeError: Event loop is closed`. These errors and exceptions do not affect test execution but they waste my test logs and reports.
The simplified python class which I import in test:
```python3
class WebsocketSubscription:

    #library can be used only in the context of a test case
    ROBOT_LIBRARY_SCOPE = 'TEST'

    def __init__(self, adr):
        self.adr = adr
        self._ws = None
        self
        self._loop = asyncio.new_event_loop()
        asyncio.set_event_loop(self._loop)
        self._loop.run_until_complete(self._ws_connect())

    async def _ws_connect(self):
        self._ws = await websockets.connect(self.adr)

    async def _ws_close(self):
        await self._ws.close()

    def ws_close(self):
        self._loop.run_until_complete(self._ws_close())
        self._loop.close()
```
Robot framework test case:
```
*** Settings ***
Library		../../libs/Tester.py

*** Test Cases ***
Import Library		Tester.WebsocketSubscription	ws://[en53:6ab7:383:2::5]:8000/
Ws Close
```

Test execution log:
```bash
==============================================================================
Test                                                               
==============================================================================
Test       							      | PASS |
------------------------------------------------------------------------------
[ ERROR ] Task was destroyed but it is pending!
task: <Task pending coro=<WebSocketCommonProtocol.transfer_data() done, defined at /home/dena/.local/lib/python3.7/site-packages/websockets/protocol.py:818> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fbb63af12d0>()]> cb=[<TaskWakeupMethWrapper object at 0x7fbb63af1390>()]>
[ ERROR ] Task was destroyed but it is pending!
task: <Task pending coro=<WebSocketCommonProtocol.keepalive_ping() done, defined at /home/dena/.local/lib/python3.7/site-packages/websockets/protocol.py:1103> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fbb63af1350>()]>>
[ ERROR ] Task was destroyed but it is pending!
task: <Task pending coro=<WebSocketCommonProtocol.close_connection() done, defined at /home/dena/.local/lib/python3.7/site-packages/websockets/protocol.py:1153> wait_for=<Task pending coro=<WebSocketCommonProtocol.transfer_data() done, defined at /home/dena/.local/lib/python3.7/site-packages/websockets/protocol.py:818> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fbb63af12d0>()]> cb=[<TaskWakeupMethWrapper object at 0x7fbb63af1390>()]>>
Exception ignored in: <coroutine object WebSocketCommonProtocol.close_connection at 0x7fbb63b3c0e0>
Traceback (most recent call last):
  File "/home/dena/.local/lib/python3.7/site-packages/websockets/protocol.py", line 1204, in close_connection
    self.transport.close()
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 653, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 683, in call_soon
    self._check_closed()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 475, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Test                                                                 | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
```

Some observations:
* Removing `Ws Close` from test case and leaving only `Import Library...` will disable these errors. 
* At first I got the same errors on class constructor execution (`Import Library...`) but `asyncio.set_event_loop(self._loop)` desabled them

Could somebody please help me to identify reason of the issue?

**Comment by danashevskiy** [comment]
Corresponding issue report on websockets page
https://github.com/aaugustin/websockets/issues/770

**Comment by danashevskiy** [comment]
I've rechecked the issue by executing python script:

```python
ws = WebSocketSubscription("ws://[en53:6ab7:383:2::5]:8000/")
ws.close()
```
and the output is clean, so issue is definitely in call chain `Robot framework - websockets - asyncio`

Could somebody please provide info on how robot framework interacts with imported python modules/submodules?

**Comment by pekkaklarck** [comment]
Sorry, I have totally missed this issue. Have you debugged the problem further? Any ideas why it could occur?
