### ISSUE TITLE
Using `Union` containing generics as type hint causes an error

### ISSUE THREAD

**Issue by Carsten-Leue** [robotframework/robotframework#3931]
With `4.0.1` I am seeing this error that does not occur on `4.0.0`:

```
Unexpected error: TypeError: Subscripted generics cannot be used with class and instance checks
Traceback (most recent call last):
  File "c:\d\hpha-robot\.tox\py38\lib\site-packages\robot\utils\application.py", line 83, in _execute
    rc = self.main(arguments, **options)
  File "c:\d\hpha-robot\.tox\py38\lib\site-packages\robot\run.py", line 447, in main
    result = suite.run(settings)
  File "c:\d\hpha-robot\.tox\py38\lib\site-packages\robot\running\model.py", line 296, in run
    self.visit(runner)
  File "c:\d\hpha-robot\.tox\py38\lib\site-packages\robot\model\testsuite.py", line 226, in visit
    visitor.visit_suite(self)
  File "c:\d\hpha-robot\.tox\py38\lib\site-packages\robot\model\visitor.py", line 85, in visit_suite
    if self.start_suite(suite) is not False:
  File "c:\d\hpha-robot\.tox\py38\lib\site-packages\robot\running\suiterunner.py", line 72, in start_suite
    ns.handle_imports()
  File "c:\d\hpha-robot\.tox\py38\lib\site-packages\robot\running\namespace.py", line 55, in handle_imports
    self._handle_imports(self._imports)
  File "c:\d\hpha-robot\.tox\py38\lib\site-packages\robot\running\namespace.py", line 66, in _handle_imports
    self._import(item)
  File "c:\d\hpha-robot\.tox\py38\lib\site-packages\robot\running\namespace.py", line 74, in _import
    action(import_setting)
  File "c:\d\hpha-robot\.tox\py38\lib\site-packages\robot\running\namespace.py", line 127, in _import_library
    lib = IMPORTER.import_library(name, import_setting.args,
  File "c:\d\hpha-robot\.tox\py38\lib\site-packages\robot\running\importer.py", line 46, in import_library
    lib = TestLibrary(name, args, variables, create_handlers=False)
  File "c:\d\hpha-robot\.tox\py38\lib\site-packages\robot\running\testlibraries.py", line 53, in TestLibrary
    lib = libclass(libcode, name, args or [], source, logger, variables)
  File "c:\d\hpha-robot\.tox\py38\lib\site-packages\robot\running\testlibraries.py", line 89, in __init__
    = self.init.resolve_arguments(args, variables)
  File "c:\d\hpha-robot\.tox\py38\lib\site-packages\robot\running\handlers.py", line 93, in resolve_arguments
    return self.arguments.resolve(args, variables)
  File "c:\d\hpha-robot\.tox\py38\lib\site-packages\robot\running\arguments\argumentspec.py", line 87, in resolve
    positional, named = converter.convert(positional, named)
  File "c:\d\hpha-robot\.tox\py38\lib\site-packages\robot\running\arguments\argumentconverter.py", line 30, in convert
    return self._convert_positional(positional), self._convert_named(named)
  File "c:\d\hpha-robot\.tox\py38\lib\site-packages\robot\running\arguments\argumentconverter.py", line 34, in _convert_positional
    converted = [self._convert(name, value)
  File "c:\d\hpha-robot\.tox\py38\lib\site-packages\robot\running\arguments\argumentconverter.py", line 34, in <listcomp>
    converted = [self._convert(name, value)
  File "c:\d\hpha-robot\.tox\py38\lib\site-packages\robot\running\arguments\argumentconverter.py", line 58, in _convert
    return converter.convert(name, value)
  File "c:\d\hpha-robot\.tox\py38\lib\site-packages\robot\running\arguments\typeconverters.py", line 91, in convert
    if self._no_conversion_needed(value):
  File "c:\d\hpha-robot\.tox\py38\lib\site-packages\robot\running\arguments\typeconverters.py", line 461, in _no_conversion_needed
    return isinstance(value, self.types)
  File "C:\Python38\lib\typing.py", line 769, in __instancecheck__
    return self.__subclasscheck__(type(obj))
  File "C:\Python38\lib\typing.py", line 777, in __subclasscheck__
    raise TypeError("Subscripted generics cannot be used with
```

It appears that the cause of the error is that an argument is a `Union` but the components of this union are indexed types. The robot framework code does an `isinstance` check for these types, but that is not allowed. Before making an instance check we need to find the non-indexed base type.

I believe the type in question is:

```
typing.Union[typing.Callable[[hpha_di.api._internal.context.Injectable[typing.Any]], hpha_di.api._internal.provider.Provider[typing.Any]], typing.AbstractContextManager[typing.Callable[[hpha_di.api._internal.context.Injectable[typing.Any]], hpha_di.api._internal.provider.Provider[typing.Any]]]]
```

**Comment by pekkaklarck** [comment]
This regression is caused by #3897. Shouldn't be overly complicated to fix. With generics we should try to find the base type, as proposed, but we probably should also handle possible other errors gracefully as well.

This is a pretty severe issue so we probably need to release 4.0 2 sooner than originally planned.

**Comment by pekkaklarck** [comment]
This ought to now be fixed. I'll create RF 4.0.2 beta 1 as soon as other issues targeted for 4.0.2 are fixed which could be already tomorrow. I hope you @Carsten-Leue can test the fixes latest then.

**Comment by pekkaklarck** [comment]
Beta is now out. Have you @Carsten-Leue had a change to test it already? We plan to release RF 4.0.2 final next Tuesday and would be great to know did the fix work and did it create new regressions before that. I would like to avoid creating RF 4.0.3 to get possible problems fixed.

**Comment by pekkaklarck** [comment]
Turned out that also `TypedDict` fails when used with `isinstance` (#3969). The fix for generics handled only them and actually made the situation with `TypedDict` even worse than it was earlier. This problem has now been fixed in more generic manner.
