### ISSUE TITLE
rebot update to ignore corrupted files

### ISSUE THREAD

**Issue by sebastianciupinski** [robotframework/robotframework#3959]
Rebot is unable to process if one of xml files is corrupted (e.g. when robot process producing output.xml has crashed)
As a result, it is unable to automatically merge many xml files if one of them is corrupted.

There is similar issue: https://github.com/robotframework/robotframework/issues/2237 where https://pypi.org/project/robotfixml/ package is proposed, but I suspect that this too may be dead as is not maintained since 2013 and not described in documentation.

**Comment by pekkaklarck** [comment]
FiXml should be resurrected. Are you interested to help with that?

**Comment by mkorpela** [comment]
```
 python3 -m pip install robotfixml
Collecting robotfixml
  Downloading robotfixml-1.0.1.tar.gz (2.8 kB)
Collecting BeautifulSoup
  Downloading BeautifulSoup-3.2.2.tar.gz (32 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-p30q7f3x/BeautifulSoup/setup.py'"'"'; __file__='"'"'/tmp/pip-install-p30q7f3x/BeautifulSoup/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-p30q7f3x/BeautifulSoup/pip-egg-info
         cwd: /tmp/pip-install-p30q7f3x/BeautifulSoup/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-p30q7f3x/BeautifulSoup/setup.py", line 3
        "You're trying to run a very old release of Beautiful Soup under Python 3. This will not work."<>"Please use Beautiful Soup 4, available through the pip package 'beautifulsoup4'."
                                                                                                        ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
This also happens now :/

**Comment by pekkaklarck** [comment]
Fixml isn't part if the core. Closing.
