### ISSUE TITLE
Second call to robot.run_cli fails

### ISSUE THREAD

**Issue by anr66** [robotframework/robotframework#3961]
When running a test from within a thread, the second call to robot.run_cli always fails when robot framework is setting up log levels. A call to logging.GetLogger().setLevel() throws an exception because setLevel somehow gets retyped as an int rather than a callable function. The only way to get around this problem was to modify pyloggingconf.py to call logging.basicConfig rather than configuring the instantiated logger.
After this error has happened, calling robot.run_cli works as expected for all subsequent tests. 

Versions: Robot Framework 3.2.2 (Python 3.7.3 on linux)
Error message:
`[ ERROR ] Unexpected error: TypeError: 'int' object is not callable
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/robot/utils/application.py", line 83, in _execute
    rc = self.main(arguments, **options)
  File "/home/pi/.local/lib/python3.7/site-packages/robot/run.py", line 439, in main
    with pyloggingconf.robot_handler_enabled(settings.log_level):
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/pi/.local/lib/python3.7/site-packages/robot/output/pyloggingconf.py", line 41, in robot_handler_enabled
    set_level(level)
  File "/home/pi/.local/lib/python3.7/site-packages/robot/output/pyloggingconf.py", line 54, in set_level
    logging.getLogger().setLevel(level)
Finished testing`

**Comment by pekkaklarck** [comment]
No new info since 2021. Closing.
