### ISSUE TITLE
Fail to load python library when executing robot with multiple robot script files 

### ISSUE THREAD

**Issue by danfengliu** [robotframework/robotframework#3972]
I got an unexpected  behavior when running command as below since upgrading robotframework from 2.9.2 to 3.2.1. I can not import python library if there are multiple robot script files following robot command:
```
robot a.robot b.robot
```
In a.robot, python package (my_package) will be  build and installed by "python ./setup.py install".
In b.robot, import a python library like:
```
*** Settings ***

Library  my_python_lib.py  
``` 
In my_python_lib.py, import my_package like:
```
import my_package 
```

**Expectation Behavior:**

my_python_lib.py can import my_package successfully.

**Actual Behavior:**

If run robot command right after reinstall setuptools then got error as below:
```
[ ERROR ] Error in file 'b.robot' on line 11: Importing library 'my_python_lib.py' failed: ModuleNotFoundError: No module named 'my_package'
Traceback (most recent call last):
  File "my_python_lib.py", line 1, in <module>
```
After that, another error will be there all the time:

```
[ ERROR ] Error in file 'b.robot' on line 11: Importing library 'my_python_lib.py' failed: ZipImportError: bad local file header: '/usr/local/lib/python3.8/dist-packages/my_package-1.0.0-py3.8.egg'
Traceback (most recent call last):
  File "my_python_lib.py", line 1, in <module>
```

My Workaround:
Until now I suppose I found 2 workarounds:
1. Replace "robot a.robot b.robot" to "robot a.robot; robot b.robot";
2. Call pip freeze by subprocess in the first place in my_python_lib.py.

Actually, this 1st workaround is not a real workaround, because it's not acceptable as for losing some functionality. And the 2nd one is kind of tricky, it will meant something for this issue.
 
**Environment:**

python: 3.6/3.7/3.8
setuptools: 56.2.0
robotframework: 3.2.1/5.1.1
OS: Ubuntu 7.5.0-3ubuntu1~18.04

**Comment by danfengliu** [comment]
Follow my first comment, a new situation occurred in my test environment, 

```
# step 1:
pip uninstall setuptools -y

# step 2:
robot a.robot; robot b.robot

# ***There will be error occurred***
[ ERROR ] Error in file 'b.robot' on line 11: Importing library 'my_python_lib.py' failed: ModuleNotFoundError: No module named 'my_package'
Traceback (most recent call last):
  File "my_python_lib.py", line 1, in <module>

# step 3:
pip install -U pip setuptools

# step 4:
robot a.robot; robot b.robot

# Then robot command executed successfully.
```
```
# step 1:
pip uninstall setuptools -y

# step 2:
pip install -U pip setuptools

# step 3:
robot a.robot; robot b.robot

# Then robot command executed successfully.
```

**Comment by pekkaklarck** [comment]
Using `robot a.robot b.robot` in general cannot be the root cause here simply because we have tests for exact that scenario and they work fine. The problem must be related to the first script installing something that the second needs. It's possible that something has changed in Robot that affects this, but the problem could also be related to Python versions or other changes.

Unfortunately it's impossible to investigate this problem with this information alone. Is it possible for you to create a simple example demonstrating the problem? Notice that the example should be as simple as possible and shouldn't contain any confidential information. For more details see http://sscce.org/.

**Comment by danfengliu** [comment]
Sorry for missing an important information in my issue description. You're quite right that "the problem must be related to the first script installing something that the second needs". In my_python_lib.py,  it imports a package ( a swagger package) which was installed (python ./setup.py install)  in file a.robot. We've been benefited from this usage for quite a long time, but it was broken since upgrading robotframework from 2.9.2 to 3.2.1, and if I move python package installation outside of robot command, which means before robot calling, then everything will be fine. but we still like the original way for our testing.

If this information is still not useful enough, I will try to create a simple example as your guidance.

Thanks!

**Comment by pekkaklarck** [comment]
This is an old and stale issue, but I decided to try reproducing it. I had earlier asked for an example, but didn't get one so I created an example myself. It contains these two files:

```robotframework
# a.robot
*** Settings ***
Library       Process

*** Test Cases ***
Install Faker
    ${result} =    Run Process    pip    install    faker    stderr=STDOUT
    Log to console    ${result.stdout}
```

```robotframework
# b.robot
*** Settings ***
Library    faker.Faker

*** Test Cases ***
Example
    ${number} =    Random Number
    Log To Console    ${number}
```

When I don't have `faker` installed and run `robot b.robot`, I get this error as expected:
> [ ERROR ] Error in file '.../b.robot' on line 2: Importing library 'faker.Faker' failed: ModuleNotFoundError: No module named 'faker'

When I run both like `robot a.robot b.robot`, `faker` is installed by `a.robot` and `b.robot` succeeds.

I suspect the original problem has been caused by system configuration or problem in tests themselves. Alternatively there has been a bug in Robot, but it has been fixed at some point.
