### ISSUE TITLE
upgrading 3.x to 4.0.3 results in Agent connection server error

### ISSUE THREAD

**Issue by valentijnpeters** [robotframework/robotframework#3995]
An internal error occurred during: "Agent connection server".
No enum constant org.rf.ide.core.execution.agent.Status.NOT RUN

**Comment by valentijnpeters** [comment]
Traceback (most recent call last):
  File "C:\Users\Valentijn\AppData\Local\Temp\RobotTempDir14761870329434815108\TestRunnerAgent.py", line 791, in _send_to_server_json
    self.decoder_encoder._write('{"%s": %s}' % (name, json_encoded_obj))
  File "C:\Users\Valentijn\AppData\Local\Temp\RobotTempDir14761870329434815108\TestRunnerAgent.py", line 847, in _write
    self._file_to_write.flush()
  File "C:\Users\Valentijn\AppData\Local\Programs\Python\Python38\lib\socket.py", line 687, in write
    return self._sock.send(b)
ConnectionAbortedError: [WinError 10053] De software op uw hostcomputer heeft een verbinding verbroken
