### ISSUE TITLE
ModuleNotFoundError: No module named 'robot'

### ISSUE THREAD

**Issue by pratapslair** [robotframework/robotframework#4024]
Hi,

I installed RPA and tried the example code below to check is it was functioning well. I am using Python 38 in Win10

from RPA.Browser.Selenium import Selenium
lib = Selenium()
lib.open_available_browser("https://example.com")
lib.input_text("id:user-name", username)
lib.input_text("id:password", password)

The following error occured

Traceback (most recent call last):

  File "C:\Users\212603475\Desktop\test.py", line 13, in <module>
    from RPA.Browser.Selenium import Selenium

  File "C:\Apps\Anaconda3\v3_8_5_x64\Local\lib\site-packages\RPA\Browser\__init__.py", line 2, in <module>
    from RPA.Browser.Selenium import Selenium as _Selenium

  File "C:\Apps\Anaconda3\v3_8_5_x64\Local\lib\site-packages\RPA\Browser\Selenium.py", line 18, in <module>
    import robot

ModuleNotFoundError: No module named 'robot'

Can yu please help find a solution?

**Comment by pekkaklarck** [comment]
The problem seems to be in the RPA module you use. Please report it to its issue tracker.
