### ISSUE TITLE
IndexError in keywordremover.py line 133

### ISSUE THREAD

**Issue by DirkRichter** [robotframework/robotframework#4063]
I run into:

[ ERROR ] Unexpected error: IndexError: list index out of range for
https://github.com/robotframework/robotframework/blob/b68e2b689515446056e53edd67bc23c4c1fd8be0/src/robot/result/keywordremover.py#L133

It seems that latest changes could result in empty list *keywords*. I still try to find/create a microsample demonstrating the issue.

Full Exception:

> [ ERROR ] Unexpected error: IndexError: list index out of range
> Traceback (most recent call last):
>   File "C:\Program Files\Python39\lib\site-packages\robot\utils\application.py", line 83, in _execute
>     rc = self.main(arguments, **options)
>   File "C:\Program Files\Python39\lib\site-packages\robot\rebot.py", line 346, in main
>     rc = ResultWriter(*datasources).write_results(settings)
>   File "C:\Program Files\Python39\lib\site-packages\robot\reporting\resultwriter.py", line 63, in write_results
>     minLevel=results.js_result.min_level)
>   File "C:\Program Files\Python39\lib\site-packages\robot\reporting\resultwriter.py", line 136, in js_result
>     self._js_result = builder.build_from(self.result)
>   File "C:\Program Files\Python39\lib\site-packages\robot\reporting\resultwriter.py", line 123, in result
>     self._result.configure(self._settings.status_rc,
>   File "C:\Program Files\Python39\lib\site-packages\robot\result\executionresult.py", line 95, in configure
>     self.suite.configure(**suite_config)
>   File "C:\Program Files\Python39\lib\site-packages\robot\result\model.py", line 472, in configure
>     self.visit(SuiteConfigurer(**options))
>   File "C:\Program Files\Python39\lib\site-packages\robot\model\testsuite.py", line 226, in visit
>     visitor.visit_suite(self)
>   File "C:\Program Files\Python39\lib\site-packages\robot\result\configurer.py", line 59, in visit_suite
>     self._remove_keywords(suite)
>   File "C:\Program Files\Python39\lib\site-packages\robot\result\configurer.py", line 65, in _remove_keywords
>     suite.remove_keywords(how)
>   File "C:\Program Files\Python39\lib\site-packages\robot\result\model.py", line 447, in remove_keywords
>     self.visit(KeywordRemover(how))
>   File "C:\Program Files\Python39\lib\site-packages\robot\model\testsuite.py", line 226, in visit
>     visitor.visit_suite(self)
>   File "C:\Program Files\Python39\lib\site-packages\robot\model\visitor.py", line 87, in visit_suite
>     suite.suites.visit(self)
>   File "C:\Program Files\Python39\lib\site-packages\robot\model\itemlist.py", line 77, in visit
>     item.visit(visitor)
>   File "C:\Program Files\Python39\lib\site-packages\robot\model\testsuite.py", line 226, in visit
>     visitor.visit_suite(self)
>   File "C:\Program Files\Python39\lib\site-packages\robot\model\visitor.py", line 87, in visit_suite
>     suite.suites.visit(self)
>   File "C:\Program Files\Python39\lib\site-packages\robot\model\itemlist.py", line 77, in visit
>     item.visit(visitor)
>   File "C:\Program Files\Python39\lib\site-packages\robot\model\testsuite.py", line 226, in visit
>     visitor.visit_suite(self)
>   File "C:\Program Files\Python39\lib\site-packages\robot\model\visitor.py", line 87, in visit_suite
>     suite.suites.visit(self)
>   File "C:\Program Files\Python39\lib\site-packages\robot\model\itemlist.py", line 77, in visit
>     item.visit(visitor)
>   File "C:\Program Files\Python39\lib\site-packages\robot\model\testsuite.py", line 226, in visit
>     visitor.visit_suite(self)
>   File "C:\Program Files\Python39\lib\site-packages\robot\model\visitor.py", line 88, in visit_suite
>     suite.tests.visit(self)
>   File "C:\Program Files\Python39\lib\site-packages\robot\model\itemlist.py", line 77, in visit
>     item.visit(visitor)
>   File "C:\Program Files\Python39\lib\site-packages\robot\model\testcase.py", line 130, in visit
>     visitor.visit_test(self)
>   File "C:\Program Files\Python39\lib\site-packages\robot\model\visitor.py", line 111, in visit_test
>     test.body.visit(self)
>   File "C:\Program Files\Python39\lib\site-packages\robot\model\itemlist.py", line 77, in visit
>     item.visit(visitor)
>   File "C:\Program Files\Python39\lib\site-packages\robot\model\keyword.py", line 98, in visit
>     visitor.visit_keyword(self)
>   File "C:\Program Files\Python39\lib\site-packages\robot\model\visitor.py", line 133, in visit_keyword
>     if self.start_keyword(kw) is not False:
>   File "C:\Program Files\Python39\lib\site-packages\robot\result\keywordremover.py", line 128, in start_keyword
>     self._remove_keywords(kw.body)
>   File "C:\Program Files\Python39\lib\site-packages\robot\result\keywordremover.py", line 133, in _remove_keywords
>     include_from_end = 2 if keywords[-1].passed else 1

Python 3.9
Robot 4.0.3
Win10

**Comment by DirkRichter** [comment]
Reason found (is not critical): 
you need the --removekeyword WUKS option in combination with an own listener which logs data for a skipped keyword *WaitUntilKeywordSucceed*. This results in this xml-snipped with a msg-node inside:
![grafik](https://user-images.githubusercontent.com/20930315/130628369-3e907d55-63e2-4903-8f7b-82bac51db86a.png)
Thus rebot runs into trouble assuming non-empty keyword WUKS.

**Comment by pekkaklarck** [comment]
Good debugging! Looking at the code, WUKS with only messages inside it definitely can cause this kind of a problem. There's first check `if kw.body` which passes because the body isn't empty due to messages but then later there are no keywords.

This is easy to fix. Need to think what's the best way to create a test for it.
