### ISSUE TITLE
Lines starting with `|` not followed by space cause crash

### ISSUE THREAD

**Issue by xbreak** [robotframework/robotframework#4082]
We started moving to Robot 4.1 (which has some really nice new features, thanks!). Running a particular test on Robot 4.0 and 4.1 failed with internal error (return code 255) which previously worked with Robot 3.x. It turns it was because it contained an Markdown-type ASCII table using pipe characters in the Comments section.

The following minimal test reproduces the problem and is caused by the pipe characters:

```robot
*** Comments ***

||

*** Test Cases ***

Do Nothing
    Log To Console  A keyword
```

**Expected result**
Comment section is ignored [as it is documented](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#id567): 

> Additional comments or data. Ignored by Robot Framework.

**Actual result**

Fails with parsing error.
Output using Robot 4.0.1 (but reproducible with robot 4.1):
```
$ robot test.robot
[ ERROR ] Unexpected error: ValueError: not enough values to unpack (expected 3, got 1)
Traceback (most recent call last):
  File "/nix/store/5jdil0g5q804ha4a61zgypwvfxwdm126-python3.8-robotframework-4.0.1/lib/python3.8/site-packages/robot/utils/application.py", line 83, in _execute
    rc = self.main(arguments, **options)
  File "/nix/store/5jdil0g5q804ha4a61zgypwvfxwdm126-python3.8-robotframework-4.0.1/lib/python3.8/site-packages/robot/run.py", line 437, in main
    suite = builder.build(*datasources)
  File "/nix/store/5jdil0g5q804ha4a61zgypwvfxwdm126-python3.8-robotframework-4.0.1/lib/python3.8/site-packages/robot/running/builder/builders.py", line 86, in build
    suite = parser.parse(structure)
  File "/nix/store/5jdil0g5q804ha4a61zgypwvfxwdm126-python3.8-robotframework-4.0.1/lib/python3.8/site-packages/robot/running/builder/builders.py", line 134, in parse
    structure.visit(self)
  File "/nix/store/5jdil0g5q804ha4a61zgypwvfxwdm126-python3.8-robotframework-4.0.1/lib/python3.8/site-packages/robot/parsing/suitestructure.py", line 44, in visit
    visitor.visit_file(self)
  File "/nix/store/5jdil0g5q804ha4a61zgypwvfxwdm126-python3.8-robotframework-4.0.1/lib/python3.8/site-packages/robot/running/builder/builders.py", line 140, in visit_file
    suite, _ = self._build_suite(structure)
  File "/nix/store/5jdil0g5q804ha4a61zgypwvfxwdm126-python3.8-robotframework-4.0.1/lib/python3.8/site-packages/robot/running/builder/builders.py", line 170, in _build_suite
    suite = parser.parse_suite_file(source, defaults)
  File "/nix/store/5jdil0g5q804ha4a61zgypwvfxwdm126-python3.8-robotframework-4.0.1/lib/python3.8/site-packages/robot/running/builder/parsers.py", line 53, in parse_suite_file
    return self._build(suite, source, defaults)
  File "/nix/store/5jdil0g5q804ha4a61zgypwvfxwdm126-python3.8-robotframework-4.0.1/lib/python3.8/site-packages/robot/running/builder/parsers.py", line 64, in _build
    model = get_model(self._get_source(source), data_only=True,
  File "/nix/store/5jdil0g5q804ha4a61zgypwvfxwdm126-python3.8-robotframework-4.0.1/lib/python3.8/site-packages/robot/parsing/parser/parser.py", line 45, in get_model
    return _get_model(get_tokens, source, data_only, curdir)
  File "/nix/store/5jdil0g5q804ha4a61zgypwvfxwdm126-python3.8-robotframework-4.0.1/lib/python3.8/site-packages/robot/parsing/parser/parser.py", line 68, in _get_model
    tokens = token_getter(source, data_only)
  File "/nix/store/5jdil0g5q804ha4a61zgypwvfxwdm126-python3.8-robotframework-4.0.1/lib/python3.8/site-packages/robot/parsing/lexer/lexer.py", line 46, in get_tokens
    lexer.input(source)
  File "/nix/store/5jdil0g5q804ha4a61zgypwvfxwdm126-python3.8-robotframework-4.0.1/lib/python3.8/site-packages/robot/parsing/lexer/lexer.py", line 82, in input
    for statement in Tokenizer().tokenize(self._read(source),
  File "/nix/store/5jdil0g5q804ha4a61zgypwvfxwdm126-python3.8-robotframework-4.0.1/lib/python3.8/site-packages/robot/parsing/lexer/tokenizer.py", line 30, in tokenize
    tokens = self._tokenize_line(line, lineno, not data_only)
  File "/nix/store/5jdil0g5q804ha4a61zgypwvfxwdm126-python3.8-robotframework-4.0.1/lib/python3.8/site-packages/robot/parsing/lexer/tokenizer.py", line 49, in _tokenize_line
    for value, is_data in splitter(rstrip(line)):
  File "/nix/store/5jdil0g5q804ha4a61zgypwvfxwdm126-python3.8-robotframework-4.0.1/lib/python3.8/site-packages/robot/parsing/lexer/tokenizer.py", line 68, in _split_from_pipes
    _, separator, rest = splitter.split(line, 1)
```

**Platform**
Reproduced with:
- Robot framework 4.0.1 from nixpkgs 21.05 using Python 3.8.9 on CentOS 8
- Robot framework 4.1 from Anaconda using Python 3.7.6 on CentOS 8

**Comment by pekkaklarck** [comment]
I can reproduce the problem. It's severe because there's a crash, but luckily just having a pipe character isn't enough to cause it. It seems to happen if you have a pipe character in the beginning of a line followed with something else than a space but a single pipe or pipe followed with a space and then whatever is fine. For example, `||`, `|||`, and `|foo` all cause problems but `|`, `| |`, `| ||` and `| foo` are all fine. Thus adding a space between those pipe characters ought to fix the issue for you while still preserving Markdown formatting. Notice also that the problem occurs everywhere, not only in the Comments section.
