### ISSUE TITLE
ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

### ISSUE THREAD

**Issue by eravion** [robotframework/robotframework#4194]
Hello,

Sometime, this function "Get Element Count xpath=..." or this one "Go To "

On multiple URL fail with this error
"ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"

When trying to do the screenshot capture.

In parallel, we are testing the same URLs with Selenium 2.53 (on more than 100 scenarios) and this function are running perfectly.
Tests (selenium 4 and 2.53) are running through the same network access.
It mean that this is not an "access to the website issue or disconnection".
Sometime, we have this error while testing URL : 'file:///etc/hostname' 

We cannot reproduce it but, we have 4 tests running 24/7 every 10 minutes.
We have the issue 10/15 time by day.

### RobotFramework debug trace :  
```shell
20220117 12:28:28.614 - INFO - +--- START KEYWORD: SeleniumLibrary.Get Element Count [ xpath=//*[@id='consent_prompt_submit'] ]
20220117 12:28:28.615 - INFO - +---- START KEYWORD: SeleniumLibrary.Capture Page Screenshot [ ]
20220117 12:28:29.011 - INFO - </td></tr><tr><td colspan="3"><a href="selenium-screenshot-1.png"><img src="selenium-screenshot-1.png" width="800px"></a>
20220117 12:28:29.011 - INFO - +---- END KEYWORD: SeleniumLibrary.Capture Page Screenshot (396)
20220117 12:28:29.015 - FAIL - ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
20220117 12:28:29.015 - DEBUG - Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/SeleniumLibrary/__init__.py", line 467, in run_keyword
    return DynamicCore.run_keyword(self, name, args, kwargs)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/SeleniumLibrary/base/robotlibcore.py", line 102, in run_keyword
    return self.keywords[name](*args, **kwargs)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/SeleniumLibrary/keywords/element.py", line 1020, in get_element_count
    return len(self.find_elements(locator))
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/SeleniumLibrary/base/context.py", line 90, in find_elements
    return self.element_finder.find(locator, tag, False, False, parent)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/SeleniumLibrary/locators/elementfinder.py", line 72, in find
    elements = strategy(criteria, tag, constraints,
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/SeleniumLibrary/locators/elementfinder.py", line 125, in _find_by_xpath
    return self._filter_elements(parent.find_elements_by_xpath(criteria),
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 537, in find_elements_by_xpath
    return self.find_elements(by=By.XPATH, value=xpath)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 1273, in find_elements
    return self.execute(Command.FIND_ELEMENTS, {
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 416, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py", line 398, in execute
    return self._request(command_info[0], url, body=data)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py", line 420, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/urllib3/request.py", line 78, in request
    return self.request_encode_body(
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/http/client.py", line 272, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
20220117 12:28:29.015 - INFO - +--- END KEYWORD: SeleniumLibrary.Get Element Count (401)
```

### Environnement :
Selenium version 4.1.1 running on docker (Grid architecture)
1 hub, multiple nodes.
All with docker selenium 4.1.1
Issue is not on one specific node.

### Library installed :
/opt/rh/rh-python38/root/usr/bin/python3 -m pip list                                               
Package                        Version  
Appium-Python-Client           1.3.0    
async-generator                1.10     
attrs                          21.2.0   
certifi                        2021.10.8
cffi                           1.15.0   
charset-normalizer             2.0.7    
cryptography                   35.0.0   
decorator                      5.1.0    
docutils                       0.17.1   
h11                            0.12.0   
idna                           3.3      
kitchen                        1.2.6    
outcome                        1.1.0    
pip                            19.3.1   
pycparser                      2.20     
pyOpenSSL                      21.0.0   
pytest-runner                  5.3.1    
requests                       2.26.0   
robotframework                 4.1.2    
robotframework-appiumlibrary   1.6.3    
robotframework-pythonlibcore   3.0.0    
robotframework-seleniumlibrary 5.1.3    
selenium                       4.1.0    
setuptools                     41.6.0   
six                            1.16.0   
sniffio                        1.2.0    
sortedcontainers               2.4.0    
trio                           0.19.0   
trio-websocket                 0.9.2    
urllib3                        1.26.7   
wsproto                        1.0.0    

First I open an issue on selenium :
https://github.com/SeleniumHQ/selenium/issues/10258
It looks the issue may also be linked to Robotframework ?

Thanks for your help.

**Comment by pekkaklarck** [comment]
Based on the traceback the error is in SeleniumLibrary or Selenium. Could also be that the used browser driver crashes and thus the connection is closed, but the other end should in that case handle the situation better as well. Anyway, this doesn't seem to caused by Robot Framework.

**Comment by swatisarraf** [comment]
@eravion eravion : I am also seeing the same error although i am using selenium=3.141 version. Did you find any resolution on this error?

**Comment by eravion** [comment]
Hello @swatisarraf : Still this issue from my side.
We are now in selenium 4.4, using the last version of docker on 40 nodes (20 Chrome and 20 Firefox).
We had this issue on all selenium 4.x version.
We have an average of 0.6% of this error by day.
No idea where the problem come from.
