### ISSUE TITLE
DateTime suffers from "Year 2038" problem with epoch conversion on 32 bit systems

### ISSUE THREAD

**Issue by juha-ylikoski** [robotframework/robotframework#4244]
## Problem

The datetime library is not able to convert timestamp in far future (Dec 31 14:10:36 2040 GMT) to epoch timestamp (integer) on 32 bit systems (like raspberry pi).

Example:

```
Convert Date    Dec 31 14:10:36 2040 GMT    date_format=%b %d %H:%M:%S %Y %Z    result_format=epoch
```

Raises
```
OverflowError: mktime argument out of range
```

This is caused by https://github.com/robotframework/robotframework/blob/208b8988254af37867d487682604f6e1229a3cf0/src/robot/libraries/DateTime.py#L576 

not handling timestamp over 32 bit integers well.

## environment

- 32 bit raspberry pi 3 
- python 3.7.3
- 3.2.1

**Comment by pekkaklarck** [comment]
It seems you have encountered [Y2038 problem](https://en.wikipedia.org/wiki/Year_2038_problem).

We possibly could workaround the issue like this:
```python
try:
    return time.mktime(dt.timetuple()) + dt.microsecond / 1e6 
except OverflowError:
    now = datetime.now()
    return time.mktime(now.timetuple()) + now.microsecond / 1e6 + (dt - now).total_seconds()
```

Could you test does the above work in your environment? There's a big risk that other code doesn't work with timestamps that cannot be represented as 32bit integers, though. If the fix works, we'd still need to make sure it works also around DST changes.

**Comment by pekkaklarck** [comment]
Already tested that DST causes problems. This is a better workaround:
```python
try:
    return time.mktime(dt.timetuple()) + dt.microsecond / 1e6 
except OverflowError:
    ok = dt.replace(year=2037)
    return time.mktime(ok.timetuple()) + ok.microsecond / 1e6 + (dt - ok).total_seconds()
```

**Comment by pekkaklarck** [comment]
Any updated to this @juha-ylikoski?

**Comment by juha-ylikoski** [comment]
@pekkaklarck  sorry for no reply. We initially fixed this internally by substracting y2037 from the DateTime object and then handling the integer conversion. (with something like `Subtract Time From Date`)

I've tested your second workaround and it does not crash but it seems that for some reason the timestamp generated is in local timezone. This seems weird to me because epoch timestamps are (to my understanding) always when possible in GMT.

We could use

```python
dt.utctimetuple()
```

to follow https://robotframework.org/robotframework/latest/libraries/DateTime.html#Epoch%20time

(this seems to have been a problem for a long time)

Though this raises another problem. It seems that `datetime.strptime` does not handle timezones making the creation of GMT timezone timestamps impossible with the example I had. (see https://stackoverflow.com/a/3306887/16544034)

My raspi has tz set to Helsinki / EEST
```
pi@raspberrypi:/tmp/robot-framework $ date +"%Z %z"
EEST +0300
```

We could try to use something else than `datetime.strptime`  (like https://stackoverflow.com/a/8525115/16544034) but dateutil module seems to also have problem with y2038 (or at least with conversion from non GMT timestamp):

```python
>>> parser.parse("Dec 31 14:10:36 2040 EET")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/.venv3/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/tmp/.venv3/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 654, in parse
    ret = self._build_tzaware(ret, res, tzinfos)
  File "/tmp/.venv3/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 1187, in _build_tzaware
    aware = self._assign_tzname(aware, res.tzname)
  File "/tmp/.venv3/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 1243, in _assign_tzname
    if dt.tzname() != tzname:
  File "/tmp/.venv3/lib/python3.7/site-packages/dateutil/tz/tz.py", line 238, in tzname
    return self._tznames[self._isdst(dt)]
  File "/tmp/.venv3/lib/python3.7/site-packages/dateutil/tz/tz.py", line 291, in _isdst
    dstval = self._naive_is_dst(dt)
  File "/tmp/.venv3/lib/python3.7/site-packages/dateutil/tz/tz.py", line 260, in _naive_is_dst
    return time.localtime(timestamp + time.timezone).tm_isdst
OverflowError: timestamp out of range for platform time_t
>>> parser.parse("Dec 31 14:10:36 2040 GMT")
datetime.datetime(2040, 12, 31, 14, 10, 36, tzinfo=tzutc())
```

## Tests
### Previous behavior

```
(.venv2) pi@raspberrypi:/tmp/robot-framework $ robot test.robot
==============================================================================
Test
==============================================================================
2040
Dec 31 14:10:36 2040 GMT
2040                                                                  | FAIL |
OverflowError: mktime argument out of range
------------------------------------------------------------------------------
2022
Dec 31 14:10:36 2022 GMT
2022                                                                  | FAIL |
Was not what https://www.epochconverter.com/ says. It should be 1672495836: 1672488636 != 1672495836
------------------------------------------------------------------------------
Test                                                                  | FAIL |
2 tests, 0 passed, 2 failed
==============================================================================
Output:  /tmp/robot-framework/output.xml
Log:     /tmp/robot-framework/log.html
Report:  /tmp/robot-framework/report.html
(.venv2) pi@raspberrypi:/tmp/robot-framework $ python3 --version
Python 3.7.3
(.venv2) pi@raspberrypi:/tmp/robot-framework $ robot --version
Robot Framework 5.0 (Python 3.7.3 on linux)
(.venv2) pi@raspberrypi:/tmp/robot-framework $ uname -a
Linux raspberrypi 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l GNU/Linux
```

### New behavior

```
(.venv3) pi@raspberrypi:/tmp/robot-framework $ robot test.robot
==============================================================================
Test
==============================================================================
2040
Dec 31 14:10:36 2040 GMT
2040                                                                  | FAIL |
Was not what https://www.epochconverter.com/ says. It should be 2240575836: 2240565036 != 2240575836
------------------------------------------------------------------------------
2022
Dec 31 14:10:36 2022 GMT
2022                                                                  | FAIL |
Was not what https://www.epochconverter.com/ says. It should be 1672495836: 1672488636 != 1672495836
------------------------------------------------------------------------------
Test                                                                  | FAIL |
2 tests, 0 passed, 2 failed
==============================================================================
Output:  /tmp/robot-framework/output.xml
Log:     /tmp/robot-framework/log.html
Report:  /tmp/robot-framework/report.html
(.venv3) pi@raspberrypi:/tmp/robot-framework $ python3 --version
Python 3.7.3
(.venv3) pi@raspberrypi:/tmp/robot-framework $ robot --version
Robot Framework 5.0.1.dev1 (Python 3.7.3 on linux)
(.venv3) pi@raspberrypi:/tmp/robot-framework $ uname -a
Linux raspberrypi 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l GNU/Linux
```

### Test case

```
*** Settings ***
Library    DateTime

***Variables***
${date1}=    Dec 31 14:10:36 2040 GMT
${date2}=    Dec 31 14:10:36 2022 GMT

***Test Cases***
2040
    Log To Console    \n${date1}
    ${epoch}=    Convert Date    ${date1}    date_format=%b %d %H:%M:%S %Y %Z    result_format=epoch
    Should Be Equal As Integers    ${epoch}    2240575836    Was not what https://www.epochconverter.com/ says. It should be 2240575836

2022
    Log To Console    \n${date2}
    ${epoch}=    Convert Date    ${date2}    date_format=%b %d %H:%M:%S %Y %Z    result_format=epoch
    Should Be Equal As Integers    ${epoch}    1672495836    Was not what https://www.epochconverter.com/ says. It should be 1672495836
```

**Comment by pekkaklarck** [comment]
Epoch time is independent on time zones. At a certain time, it's the same everywhere. This was lately discussed as part of  #4322 and the docs were enhanced related to it.

A problem with parsing dates like `Dec 31 14:10:36 2040 GMT` is that `datetime.strptime` returns [naive dates](https://docs.python.org/3/library/datetime.html#aware-and-naive-objects) (i.e. dates without time zone information) and thus the `GMT` part is in practice ignored:
```python
>>> d = datetime.strptime('Dec 31 14:10:36 2040 GMT', '%b %d %H:%M:%S %Y %Z')
>>> print(d)
2040-12-31 14:10:36
>>> d.timestamp()
2240568636.0
>>> d == datetime.strptime('Dec 31 14:10:36 2040', '%b %d %H:%M:%S %Y')
True
```
I don't have any idea how to solve this, but the issue isn't really related to the Y2038 problem.

**Comment by pekkaklarck** [comment]
Notice that the DateTime library in general doesn't support time zones well. The main reason is that the underlying datetime module doesn't support them too well either. The support has got better in the latest Python versions, but there's still no built-in time zone support. Python 3.9 added [zoneinfo](https://docs.python.org/3/library/zoneinfo.html), but it relies on the system time zone date or an installed third party module. Anyway, better time zone support would require its own issue.

**Comment by pekkaklarck** [comment]
I did some cleanup to DateTime code [few days ago](ebbcd9580d1a1a34a048e6dbb2fdd14e274b23e9) and one of the changes was changing
```python
time.mktime(dt.timetuple()) + dt.microsecond / 1e6
```
to
```python
dt.timestamp()
```
The change will be in the forthcoming RF 7.0 rc 1 and it would be great if you @juha-ylikoski could test does it fix this issue.

**Comment by juha-ylikoski** [comment]
I guess you are referring to commit id ebbcd9580d1a1a34a048e6dbb2fdd14e274b23e9 (the link was broken).

I have installed the version by creating a new python virtual env and installing the robotframework with:
```bash
python3 -m venv .venv
source .venv/bin/activate
pip3 install git+https://github.com/robotframework/robotframework.git@ebbcd9580d1a1a34a048e6dbb2fdd14e274b23e9
```

And run a test case with:

```robot
*** Settings ***
Library    DateTime

***Variables***
${date1}=    Dec 31 14:10:36 2040 GMT

***Test Cases***
2040
    Log To Console    \n${date1}
    ${epoch}=    Convert Date    ${date1}    date_format=%b %d %H:%M:%S %Y %Z    result_format=epoch
    Should Be Equal As Integers    ${epoch}    2240575836    Was not what https://www.epochconverter.com/ says. It should be 2240575836

```

And got:

```
==============================================================================
Testcase                                                                      
==============================================================================
2040                                                                  
Dec 31 14:10:36 2040 GMT
2040                                                                  | FAIL |
OverflowError: timestamp out of range for platform time_t
------------------------------------------------------------------------------
Testcase                                                              | FAIL |
1 test, 0 passed, 1 failed
==============================================================================
Output:  /tmp/test/output.xml
Log:     /tmp/test/log.html
Report:  /tmp/test/report.html
```

I tried to convert a datetime to integer with year>2040:

```python3
>>> import datetime
>>> d=datetime.datetime(2040, 12, 20, 8, 19, 3, 224927)
>>> d.timestamp()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: timestamp out of range for platform time_t
```

I think this is relevant bug in python datetime library: https://github.com/python/cpython/issues/101069


---

Version info:

```bash
$ python3 --version
Python 3.9.2
$ uname -a
Linux <redacted> 5.15.61-v7+ #1578 SMP Wed Aug 24 11:46:41 BST 2022 armv7l GNU/Linux
$ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

Was run with raspberry pi 3B

**Comment by pekkaklarck** [comment]
I was hoping that avoiding `time.mktime` would solve this but also afraid that `datetime` itself could have issues. Unfortunately my worries realized.

The issue you found certainly looks relevant. Have you looked does the workaround explained in the following comment work in your environment?

https://github.com/python/cpython/issues/101069#issuecomment-1665453031

**Comment by pekkaklarck** [comment]
Also, could you run tests with `--loglevel debug` that we get a traceback and see where exactly the conversion fails?

**Comment by pekkaklarck** [comment]
This workaround, based on my earlier workaround attempt, could be tested as well:
```python
try:
    return dt.timestamp()
except OverflowError:
    ok = dt.replace(year=2037)
    return ok.timestamp() + (dt - ok).total_seconds()
```

**Comment by juha-ylikoski** [comment]
I can deserialize a timestamp in 2065 with:

```python3
>>> import datetime
>>> print(datetime.datetime.utcfromtimestamp(0)+datetime.timedelta(seconds=3000000000))
2065-01-24 05:20:00
```

And I tested that also this works:

```python3
>>> import datetime
>>> datetime.datetime.utcfromtimestamp(0)+datetime.timedelta(seconds=3000000000)
datetime.datetime(2065, 1, 24, 5, 20)
>>> d = datetime.datetime(2060, 12, 20, 8, 46, 34, 384805)
>>> d.timestamp()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: timestamp out of range for platform time_t
>>> dd = datetime.datetime(2060, 12, 20, 8, 46, 34, 384805) - datetime.datetime.utcfromtimestamp(0)
>>> type(dd)
<class 'datetime.timedelta'>
>>> dd.total_seconds()
2870757994.384805
```

Meaning there could be a hacky workaround for this issue in robotframework, but it should be in reality fixed by python datetime library.

---

Same test as above with `--loglevel trace`:

![image](https://github.com/robotframework/robotframework/assets/59252246/0606ab17-95df-4f65-8b4d-6fdb872d8a74)

Does not really show what crashes but at the very least the `.timestamp()` will crash with this date.


---

Your workaround seems to be working (like my example above):

```python3
>>> import datetime
>>> dt = datetime.datetime(2060, 12, 20, 8, 46, 34, 384805)
>>> try:
...     print(dt.timestamp())
... except OverflowError:
...     ok = dt.replace(year=2037)
...     print(ok.timestamp() + (dt - ok).total_seconds())
... 
2870757994.3848047
```

And modifying the robot files:

```python3
    def _convert_to_epoch(self, dt):
        try:
            return dt.timestamp()
        except OverflowError:
            ok = dt.replace(year=2037)
            return ok.timestamp() + (dt - ok).total_seconds()

```
Seems to also work:

```bash
robot tc.robot 
==============================================================================
Tc                                                                            
==============================================================================
2040                                                                  
Dec 31 14:10:36 2040 GMT
2040                                                                  | PASS |
------------------------------------------------------------------------------
Tc                                                                    | PASS |
1 test, 1 passed, 0 failed
==============================================================================
Output:  /tmp/test/output.xml
Log:     /tmp/test/log.html
Report:  /tmp/test/report.html
```

**Comment by pekkaklarck** [comment]
We have some success! I agree this should be fixed in Python, but the workarounds for handling Unix timestamps in output and input look simple enough to be added to DateTime.

I can make changes to Robot's code soon. Could you then test the updated version in your environment?

**Comment by juha-ylikoski** [comment]
I can.

**Comment by pekkaklarck** [comment]
I committed changes and the wording in the commit message automatically closed this issue. I'll reopen it now, but if the workaround works we can close this for good.

The commit contains fix only for the issue with conversion to epoch. I attempted to add a workaround also for conversion from epoch, but that got annoyingly complicated with DST issues and with `utcfromtimestamp` being deprecated. Nobody has reported that particular issue so I decided not to spend more time with it.

I also tried to reproduce this issue on Windows with a 32bit Python installation. That wasn't affected by the Python bug so the attempt failed. I guess I could reproduce the issue on my Linux machine, but I don't have interest to study how I could install 32bit Python there.

**Comment by pekkaklarck** [comment]
Ooops, I accidentally committed this code:
```python
    def _convert_to_epoch(self, dt):
        try:
            raise OverflowError
            return dt.timestamp()
        except OverflowError:
            # Y2038 bug: https://github.com/python/cpython/issues/101069
            ok = dt.replace(year=2037)
            return ok.timestamp() + (dt - ok).total_seconds()
```
That `raise OverflowError` was there to test that the workaround works at least on my environment. It worked also on CI so clearly the code works at least on 64bit systems. I'll remove the `raise` line shortly.

I also realized that the DST issue I has with conversion from epoch was actually a problem in the test I created. I left the test there and it failed on CI. Perhaps I give another attempt to fix the from epoch issue.

**Comment by pekkaklarck** [comment]
New version with the `raise OverflowError` removed and with a workaround for conversion from epoch committed. These examples ought to validate the behavior both with and without DST:
```
    ${secs} =    Convert Date    ${5000000000}    result_format=epoch
    Should Be Equal    ${secs}     ${5000000000}
    ${secs} =    Convert Date    ${6000000000}    result_format=epoch
    Should Be Equal    ${secs}     ${6000000000}
```

**Comment by juha-ylikoski** [comment]
Now the 2040 works but the larger ones do not:

```bash
$ cat tc.robot 
*** Settings ***
Library    DateTime

***Variables***
${date1}=    Dec 31 14:10:36 2040 GMT

***Test Cases***
2040
    Log To Console    \n${date1}
    ${epoch}=    Convert Date    ${date1}    date_format=%b %d %H:%M:%S %Y %Z    result_format=epoch
    Should Be Equal As Integers    ${epoch}    2240575836    Was not what https://www.epochconverter.com/ says. It should be 2240575836

5000000000
    ${secs} =    Convert Date    ${5000000000}    result_format=epoch
    Should Be Equal    ${secs}     ${5000000000}
6000000000
    ${secs} =    Convert Date    ${6000000000}    result_format=epoch
    Should Be Equal    ${secs}     ${6000000000}
$ robot tc.robot
==============================================================================
Tc                                                                            
==============================================================================
2040                                                                  
Dec 31 14:10:36 2040 GMT
2040                                                                  | PASS |
------------------------------------------------------------------------------
5000000000                                                            | FAIL |
OverflowError: timestamp out of range for platform time_t
------------------------------------------------------------------------------
6000000000                                                            | FAIL |
OverflowError: timestamp out of range for platform time_t
------------------------------------------------------------------------------
Tc                                                                    | FAIL |
3 tests, 1 passed, 2 failed
==============================================================================
Output:  /tmp/test/output.xml
Log:     /tmp/test/log.html
Report:  /tmp/test/report.html
```

version was installed with:
```bash
pip3 install git+https://github.com/robotframework/robotframework.git@ad4cf1ab17051c76cac19f823da3ef1ba6318ae6
```
And the environment is otherwise the same as earlier.

**Comment by pekkaklarck** [comment]
There's clearly some other limitation now. Can you test how big years still work? If the limit is high enough, we can consider this issue resolved.

**Comment by pekkaklarck** [comment]
I added this to RF 7.0 scope so that it will be included the release notes. If it turns out the limit was raised only few years from 2038, we can still remove it.

**Comment by juha-ylikoski** [comment]
The conversions seem to now be not crashing, but your addition of additional daylight saving time is breaking it.

```robot
*** Settings ***
Library    DateTime

***Variables***
${i31_m_1}=    Jan 19 03:14:07 2038 GMT
${i31}=    Jan 19 03:14:08 2038 GMT
${large}=    Dec 21 07:26:52 9999 GMT

**Test Cases***
2147483647 to date
    ${secs} =    Convert Date    ${2147483647}    result_format=epoch
    Should Be Equal    ${secs}     ${2147483647.0}
2147483647 from date
    ${epoch}=    Convert Date    ${i31_m_1}    date_format=%b %d %H:%M:%S %Y %Z    result_format=epoch
    Should Be Equal As Integers    ${epoch}    2147483647    Was not what https://www.epochconverter.com/ says. It should be 2147483647

2147483648 to date
    ${secs} =    Convert Date    ${2147483648}    result_format=epoch
    Should Be Equal    ${secs}     ${2147483648.0}
2147483648 from date
    ${epoch}=    Convert Date    ${i31}    date_format=%b %d %H:%M:%S %Y %Z    result_format=epoch
    Should Be Equal As Integers    ${epoch}    2147483648    Was not what https://www.epochconverter.com/ says. It should be 2147483648

253401377212 to date
    ${secs} =    Convert Date    ${253401377212}    result_format=epoch
    Should Be Equal    ${secs}     ${253401377212.0}
253401377212 from date
    ${epoch}=    Convert Date    ${large}    date_format=%b %d %H:%M:%S %Y %Z    result_format=epoch
    Should Be Equal As Integers    ${epoch}    253401377212    Was not what https://www.epochconverter.com/ says. It should be 253401377212

```

```bash
robot --loglevel trace tc.robot 
==============================================================================
Tc                                                                            
==============================================================================
2147483647 to date                                                    | PASS |
------------------------------------------------------------------------------
2147483647 from date                                                  | PASS |
------------------------------------------------------------------------------
2147483648 to date                                                    | FAIL |
2147487248.0 != 2147483648.0
------------------------------------------------------------------------------
2147483648 from date                                                  | PASS |
------------------------------------------------------------------------------
253401377212 to date                                                  | FAIL |
253401380812.0 != 253401377212.0
------------------------------------------------------------------------------
253401377212 from date                                                | PASS |
------------------------------------------------------------------------------
Tc                                                                    | FAIL |
6 tests, 4 passed, 2 failed
==============================================================================
Output:  /tmp/test/output.xml
Log:     /tmp/test/log.html
Report:  /tmp/test/report.html
```
![image](https://github.com/robotframework/robotframework/assets/59252246/c227bb02-f9f4-46b3-9291-c5d8bf18356c)

---

I'm not exactly sure why you added this extra subtraction.

```python3
    def _epoch_seconds_to_datetime(self, secs):
        try:
            return datetime.datetime.fromtimestamp(secs)
        except OverflowError:
            # Y2038 bug: https://github.com/python/cpython/issues/101069
            # We use local times and need to handle DST separately here.
            dt = datetime.datetime.fromtimestamp(0) + datetime.timedelta(seconds=secs)
            dst_difference = time.altzone - time.timezone
            if dst_difference and self._convert_to_epoch(dt) - secs == dst_difference:
                return dt - datetime.timedelta(seconds=dst_difference)          # <------------
            return dt
```
I have understood that epoch time is always without timezone/ in GMT and there is no daylight saving time. I suggest we change it to:


```python3
    def _epoch_seconds_to_datetime(self, secs):
        try:
            return datetime.datetime.fromtimestamp(secs)
        except OverflowError:
            # Y2038 bug: https://github.com/python/cpython/issues/101069
            dt = datetime.datetime.fromtimestamp(0) + datetime.timedelta(seconds=secs)
            return dt
```

I also think that your implementation of:

```python3

    def _convert_to_epoch(self, dt):
        try:
            return dt.timestamp()
        except OverflowError:
            # Y2038 bug: https://github.com/python/cpython/issues/101069
            ok = dt.replace(year=2037)
            return ok.timestamp() + (dt - ok).total_seconds()
```
Has a timezone/daylight savings time problem but I have no idea currently on how to fix it. I tried to reproduce it in pure python:

```python3
>>> t = 1703146154
>>> datetime.datetime.fromtimestamp(0) + datetime.timedelta(seconds=t)
datetime.datetime(2023, 12, 21, 9, 9, 14)
>>> datetime.datetime.fromtimestamp(t)
datetime.datetime(2023, 12, 21, 8, 9, 14)
```

And got not so nice results... No idea how I ended up getting 09:09:14 from this timedelta version but what it should have given me was either:

GMT: Thursday, December 21, 2023 8:09:14 AM
or 
Your time zone: Thursday, December 21, 2023 10:09:14 AM [GMT+02:00]

According to [epoch converter](https://www.epochconverter.com/)

I guess this also has something to do with DST but damn I'm confused why I'm getting DST when I add a timedelta to a datetime created from timestamp but not directly to the datetime created from timestamp.

**Comment by pekkaklarck** [comment]
The reason for the DST hack was that without it I got different results than with `datetime.fromtimestamp`. Dates that ended up being in the normal time were ok, but if they were in the summer time there was a difference. By subtracting the difference between the normal and the summer time I got same results locally consistently. It also worked on CI on Linux but strangely failed on Windows. This is strange stuff...

`datetime.utcfromtimestamp` wouldn't suffer from these issues, but because we otherwise normally use local times, the results wouldn't be correct either.

It might be best that I remove the workaround for using epoch seconds in input altogether.

**Comment by pekkaklarck** [comment]
I didn't get DST problems with the epoch output workaround and tests pass locally and on CI. The algorithm also looks DST safe, because it compares dates with same month and day but on differ, so they should have same DST status.

**Comment by juha-ylikoski** [comment]
@pekkaklarck do you know in what timezone the CI is configured in? Usually when I've been running servers, I have them in utc time. This could also make the test cases seem to work in CI when in reality it just happens to match the timezone of the timestamp.

**Comment by pekkaklarck** [comment]
I would assume they use UTC, but interestingly there were some differences between Linux and Windows. In general tests should succeed on any time zone.

**Comment by pekkaklarck** [comment]
It seems getting this properly fixed in RF 7.0 isn't possible or at least worth the effort. I believe it's better the keywords fail than produce invalid results. I'll revert both of the workarounds and remove this issue from RF 7.0 scope.

We can return to this in RF 7.1 or, because this is a bug, already in RF 7.0.1. I believe the best approach would be that you @juha-ylikoski try to create workarounds yourself because you can then directly test them in your environment. I can then review them and test that they work the same way as the normal functionality elsewhere.

When testing this, I recommend you use dates in format like `2023-12-21 13:29:01.123` instead of anything that requires using a custom input format and especially instead of anything having a timezone. That just adds extra complexity, and that conversion itself may have problems, which makes understanding results harder. If you encounter problems, please include tracebacks here as text.
