### ISSUE TITLE
Executing RobotFramework from PyInstaller generated exe gives error that log.html can't be found

### ISSUE THREAD

**Issue by evmehok** [robotframework/robotframework#4382]
Python version: Python 3.10.5
RF version: Robot Framework 5.0.1 (Python 3.10.5 on win32)
PyInstaller Version: 5.1
OS: Windows 10, build 19044.1766

I'm trying to package RobotFramework into an executable with PyInstaller. We have a packaged script which calls the robot file using robot.run('test.robot'). Robot file is not packaged in the executable.
When the executable is run, I get this output and error:

```
PS C:\Users\Name\PythonProjects\output> .\main.exe
==============================================================================
Test
==============================================================================
test                                                                  .func
test                                                                  | PASS |
------------------------------------------------------------------------------
Test                                                                  | PASS |
1 test, 1 passed, 0 failed
==============================================================================
Output:  C:\Users\Name\PythonProjects\output\output.xml
[ ERROR ] Unexpected error: FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Name\\AppData\\Local\\Temp\\_MEI144002\\robot\\htmldata\\rebot\\log.html'
Traceback (most recent call last):
  File "robot\utils\application.py", line 81, in _execute
  File "robot\run.py", line 456, in main
  File "robot\reporting\resultwriter.py", line 63, in write_results
  File "robot\reporting\resultwriter.py", line 77, in _write_log
  File "robot\reporting\resultwriter.
py", line 84, in _write
  File "robot\reporting\logreportwriters.py", line 43, in write
  File "robot\reporting\logreportwriters.py", line 36, in _write_file
  File "robot\htmldata\htmlfilewriter.py", line 33, in write
  File "robot\htmldata\template.py", line 27, in __iter__
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Name\\AppData\\Local\\Temp\\_MEI144002\\robot\\htmldata\\rebot\\log.html'
```
Steps to reproduce:
1. Open attached zip files, which contain my exe but also files to generate it again
2. [Project_Files.zip](https://github.com/robotframework/robotframework/files/8986821/Project_Files.zip)
3. Use PyInstaller command to generate own exe (modify abs paths as necessary)
4. `python -m PyInstaller --noconfirm --onefile --console --add-data "C:/Users/Name/PythonProjects/test.py;."  "C:/Users/Name/PythonProjects/main.py"`
5. Place 'test.robot' into folder with generated 'main.exe'
6. Execute 'main.exe' (either clicking or calling 'main.exe' from Power Shell)
7. See test passes, but that it cannot generate log files correctly due to above error. 

Also, I'll show preview of each file:

main.py:
```
import robot
import robot.libraries.BuiltIn
import robot.libraries.Reserved
import robot.libraries.Easter

robot.run("test.robot")
# Command line arg doesn't work either:
# robot.run("test.robot", outputdir='C:\\Users\\Name\\PythonProjects\\output', log='C:\\Users\\Name\\PythonProjects\\output\\log2.html')
```
test.py:
```
from robot.api import logger

def func():
    logger.console("func test.")
```

test.robot:
```
*** Settings ***
Library      test.py


*** Test Case ***

test
    func
```

**Comment by evmehok** [comment]
Hi @pekkaklarck thank you for the detailed response! This actually helped greatly with debugging the issue. I tried the solutions you suggested, which did not seem to work here. I later found out that when PyInstaller gathers the resources for Robot Framework in the executable, it seems to be leaving out those template files in ..\robot\htmldata\rebot\.
I was able to work-around this by explicitly adding the folder to the PyInstaller Executable. 

Thanks again for your help! I'll close this issue.

**Comment by AlexMM98** [comment]
Hello @evmehok I'm interested in doing exactly the same thing as you: making an executable of a robot framework code with PyInstaller, but I have the same problem. To fix this, did you add a Temp folder to the pathex of the .spec file? I've tried with the robot source folders, but it doesn't seem to work.
Can you give me a hand? Thank you and regards

**Comment by cardenal17** [comment]
Hola @evmehok  tengo el mismo problema porfa me podrías ayudar con este caso

**Comment by evmehok** [comment]
Hi @cardenal17 @AlexMM98 , 

I solved this by adding the robot\ folder installed by pip to the '--add-data' flag. 

So it would look something like: `... --add-data \*pathToPython*\Python\site-packages\robot ...`

The problem is that the resources necessary for creating some of the output files aren't automatically gathered when using PyInstaller. The solution isn't necessary elegant, but seems to work for me. 

The files it was complaining about missing for me were located here: `\*pathToPython*\Python\site-packages\robot\htmldata\rebot` and seem to be used for generating reports.

**Comment by cardenal17** [comment]
hola que tal es que lo intente y me salio esto:

`
Traceback (most recent call last):
  File "login.py", line 6, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "src\userinterface\home.py", line 6, in <module>
    from robot import *
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "robot\__init__.py", line 44, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "robot\rebot.py", line 40, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "robot\conf\__init__.py", line 27, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "robot\conf\settings.py", line 22, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "robot\output\__init__.py", line 22, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "robot\output\output.py", line 16, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "robot\output\pyloggingconf.py", line 19, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "robot\utils\__init__.py", line 36, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "robot\utils\argumentparser.py", line 28, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "robot\utils\misc.py", line 21, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "robot\utils\robottypes.py", line 25, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "robot\utils\robottypes3.py", line 16, in <module>
ImportError: cannot import name 'Mapping' from 'collections' (C:\Users\uriel\Desktop\carpetas\python\robot\output\login\base_library.zip\collections\__init__.pyc)
`

**Comment by cardenal17** [comment]
Este es el comando 
`pyinstaller --noconfirm --onedir --windowed --icon "C:/Users/{username}/Desktop/carpetas/python/robot/images/favicon.ico" --add-data "C:/Users/{username}/Desktop/carpetas/python/robot/global;global/" --add-data "C:/Users/{username}/Desktop/carpetas/python/robot/images;images/" --add-data "C:/Users/{username}/Desktop/carpetas/python/robot/output;output/" --add-data "C:/Users/{username}/Desktop/carpetas/python/robot/results;results/" --add-data "C:/Users/{username}/Desktop/carpetas/python/robot/src;src/" --collect-data "customtkinter" --add-data "C:/Users/{username}/AppData/Local/Programs/Python/Python310/Lib/site-packages/robot;robot/" --add-data "C:/Users/{username}/AppData/Local/Programs/Python/Python310/Lib/site-packages/robot/htmldata/rebot;rebot/"  "C:/Users/{username}/Desktop/carpetas/python/robot/login.py" 
`

**Comment by allenyllee** [comment]
Here's my solution:

run_tests.py
```python
from robot import run

if __name__ == "__main__":
    run("test.robot")
```

run_tests.spec
```python
# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['run_tests.py'],
    pathex=[],
    binaries=[('/usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0','.')],
    datas=[('test.robot','.'), ('/usr/local/lib/python3.10/dist-packages/robot/htmldata','./robot/htmldata')],
    hiddenimports=['robot.libraries.BuiltIn', 'robot.libraries.Easter'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='run_tests',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

```

build command:

```shell
pyinstaller run_tests.spec
```
