### ISSUE TITLE
[BUG] Invalid parsing of reused variables in ***VARIABLES*** section

### ISSUE THREAD

**Issue by mkaskow** [robotframework/robotframework#4544]
## 1. VERSION INFORMATION

- Robot Framework 5.0.1
- Python 3.9.10
- macOS 10.15

## 2. STEPS

I'd like to reuse variables to create new ones.

When I try to load it into ROBOT model, cannot parse `${var2}` - check traceback below.

I can create a workaround, check variables store items with regex `r"(\$\{.+\})"` and replace value with actual one, but then emitting a ROBOT will replace my second variable with value `${var2}=  Say Hi!` - which is not what I want. Seems problem 

#### ROBOT

```robotframework
***VARIABLES***
${var1}      Hi!
${var2}      Say ${var1}
```
## 3. TRACEBACK

```shell
Error in file '<_io.TextIOWrapper name='tests\\mdcli.robot' mode='r' encoding='utf-8'>' on line 22: Setting variable '${var2}' failed: Variable '${var1}' not found.
Traceback (most recent call last):
  File "C:\Users\johndoe\venv\lib\site-packages\robot\variables\store.py", line 46, in _resolve_delayed
    self.data[name] = value.resolve(self._variables)
  File "C:\Users\johndoe\venv\lib\site-packages\robot\variables\tablesetter.py", line 69, in resolve
    return self._replace_variables(self._values, variables)
  File "C:\Users\johndoe\venv\lib\site-packages\robot\variables\tablesetter.py", line 105, in _replace_variables
    return variables.replace_scalar(values[0])
  File "C:\Users\johndoe\venv\lib\site-packages\robot\variables\variables.py", line 55, in replace_scalar
    return self._replacer.replace_scalar(item, ignore_errors)
  File "C:\Users\johndoe\venv\lib\site-packages\robot\variables\replacer.py", line 83, in replace_scalar
    return self._replace_scalar(match, ignore_errors)
  File "C:\Users\johndoe\venv\lib\site-packages\robot\variables\replacer.py", line 92, in _replace_scalar
    return self.replace_string(match, ignore_errors=ignore_errors)
  File "C:\Users\johndoe\venv\lib\site-packages\robot\variables\replacer.py", line 104, in replace_string
    return self._replace_string(match, unescaper, ignore_errors)
  File "C:\Users\johndoe\venv\lib\site-packages\robot\variables\replacer.py", line 111, in _replace_string
    safe_str(self._get_variable_value(match, ignore_errors))
  File "C:\Users\johndoe\venv\lib\site-packages\robot\variables\replacer.py", line 125, in _get_variable_value
    value = self._finder.find(match)
  File "C:\Users\johndoe\venv\lib\site-packages\robot\variables\finders.py", line 49, in find
    variable_not_found(name, self._store.data)
  File "C:\Users\johndoe\venv\lib\site-packages\robot\variables\notfound.py", line 33, in variable_not_found
    raise VariableError(message)
robot.errors.VariableError: Variable '${var1}' not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\johndoe\getvars.py", line 12, in <module>
    model = load_model(getLogger("SATS VARS"), f)
  File "C:\Users\johndoe\venv\lib\site-packages\oatscommon\robot_models.py", line 990, in load_model
    suites = RobotTestSuite.create_models(log, test_settings, suite)
  File "C:\Users\johndoe\venv\lib\site-packages\oatscommon\robot_models.py", line 883, in create_models
    variables = RobotVariable.create_models(log, variable_store.as_dict())
  File "C:\Users\johndoe\venv\lib\site-packages\robot\variables\store.py", line 125, in as_dict
    return NormalizedDict(variables,  ignore='_')
  File "C:\Users\johndoe\venv\lib\site-packages\robot\utils\normalizing.py", line 65, in __init__
    self._add_initial(initial)
  File "C:\Users\johndoe\venv\lib\site-packages\robot\utils\normalizing.py", line 69, in _add_initial
    for key, value in items:
  File "C:\Users\johndoe\venv\lib\site-packages\robot\variables\store.py", line 122, in <genexpr>
    variables = (self._decorate(name, self[name]) for name in self)
  File "C:\Users\johndoe\venv\lib\site-packages\robot\variables\store.py", line 64, in __getitem__
    return self._resolve_delayed(name, self.data[name])
  File "C:\Users\johndoe\venv\lib\site-packages\robot\variables\store.py", line 52, in _resolve_delayed
    variable_not_found('${%s}' % name, self.data)
  File "C:\Users\johndoe\venv\lib\site-packages\robot\variables\notfound.py", line 33, in variable_not_found
    raise VariableError(message)
robot.errors.VariableError: Variable '${var2}' not found.
```

I've examined ```TestSuite().resource.variables``` object and got `Variable()` objects with:

```bash
name: ${var1}
value: ("Hi!",)

name: ${var2}
value: ("Say ${var1}",)
```

**Comment by pekkaklarck** [comment]
I cannot reproduce the problem with these instructions.

**Comment by mkaskow** [comment]
```python
from typing import TextIO

from robot.conf import RobotSettings
from robot.errors import VariableError
from robot.running.builder.parsers import RobotParser
from robot.running.model import (
    Import,
    TestSuite,
)
from robot.variables.scopes import GlobalVariables
from robot.variables.tablesetter import VariableTableSetter
from robot.variables.variables import VariableStore


class RobotVariableImport(object):
    """Represents an imported variable file, along with its arguments."""

    __slots__ = ["name", "args"]

    def __init__(self, name: str, args: list[str]):
        self.name = name
        self.args = args


def load_model(
    robot_data: TextIO,
):
    suite = TestSuite(name="Parsed Suite", source=robot_data)
    suite = RobotParser()._build(suite, robot_data, None)

    test_settings = RobotSettings()
    variables = create_models(test_settings, suite)

    return variables


def create_models(test_settings: RobotSettings, raw_definition: TestSuite):
    """
    Creates suite models from given raw definitions.

    Args:
        log (Logger): Logger to write output to.
        test_settings (RobotSettings): Settings to pass to RF when parsing.
        *raw_definitions (TestSuite): Collection of test suites to create modes from.
    """
    suite: TestSuite = raw_definition

    if len(suite.tests) or len(suite.resource.keywords):
        variable_files = []
        for suite_import in suite.resource.imports:
            import_data: Import = suite_import
            if import_data.type == "Variables":
                variable_files.append(
                    RobotVariableImport(
                        import_data.name,
                        list(import_data.args or ()),
                    )
                )

        global_variables = GlobalVariables(test_settings)
        variable_store = VariableStore(global_variables)
        variable_setter = VariableTableSetter(variable_store)

        print("\n\nVARIALES LIST")
        for var in suite.resource.variables:
            print(f"name: {var.name}")
            print(f"source: {var.source}")
            print(f"value: {var.value}\n")

        print("\n\nGLOBAL VARIABLES LIST")
        print(variable_store._variables.as_dict())

        # set variables
        variable_setter.set(suite.resource.variables)
        tmp_vars = variable_store.as_dict(0)
        return tuple(map(lambda x: {x[0]: x[1]._values[1][0]}, tmp_vars.items()))


vars = load_model("test.robot")
print(f"Vars {type(vars)}")
print(vars)
```

`VariableTableSetter().set(variables, overwrite=False)` executes
`self._store.add(name, value, overwrite, decorated=False)` method.

Went down for and checked it.

`VariableStore.add()` adds variables to `VariableStore().data` normalized dict:

```python
{
    'VAR1': <robot.variables.tablesetter.ScalarVariableTableValue object at 0x000001E759FA0F10>,
    'VAR2': <robot.variables.tablesetter.ScalarVariableTableValue object at 0x000001E759FA0880>
}
```

I've imported and checked what are the values.

```python
from robot.variables.tablesetter import ScalarVariableTableValue
```

It inherits from `VariableTableValueBase` class, whose `_values` attribute returns a tuple `(None, ('Hi!',))` for `${VAR1}` and `(None, ('Say ${VAR1}',))` for `${VAR2}`. Don't know why 1st element is `NoneType` though, but it seems so far so good.

The problem seems to be located in `tmp_vars = variable_store.as_dict()` which is `VariableStore().as_dict(decorator=True)` method. If I set `as_dict(False)` it does what the trick, but value is not resolved.

```powershell
C:\Users\kaskow\Desktop\New folder> python test.py


VARIALES IN ROBOT SUITE
name: ${VAR1}
source: test.robot
value: ('Hi!',)

name: ${VAR2}
source: test.robot
value: ('Say ${VAR1}',)

Vars <class 'tuple'>
({'VAR1': 'Hi!'}, {'VAR2': 'Say ${VAR1}'})
```

**Comment by mkaskow** [comment]
I need decorated variable with `$`, `%` or `@` and curly braces to identify variable type.

What seems to be is that variables from `***VARIALES***` section are not registered by ` VariableTableSetter().set()` -> `VariablesStore().add()` methods. It adds it to `VariableStore().data` dictionary, but `VariableStore()._resolve_delayed()` method handles `DataError` exception, as variable value is not found in `VariableStore()._variables` - only in `data` attribute.

```python
def _resolve_delayed(self, name, value):
    if not self._is_resolvable(value):
        return value
    try:
        self.data[name] = value.resolve(self._variables)
    except DataError as err:
        # Recursive resolving may have already removed variable.
        if name in self.data:
            self.data.pop(name)
            value.report_error(err)
        variable_not_found('${%s}' % name, self.data)
```

**Comment by pekkaklarck** [comment]
This looks pretty complicated and I don't have time to look at it closely now and probably not in the neat future either. This also seems to be using Robot's internal modules in ways that may break in future versions. 

Could you clarify what you are trying to accomplish? Perhaps there's a better way to do it. Also, if you can create a simpler example I could test locally, I could perhaps take a look at it some time next week.

**Comment by mkaskow** [comment]
I'm loading ROBOT suite into a model and decompose it into settings, variables, test cases etc. In general, I want to have an object of a Test Suite with some extra stuff added.

The Problem here is that VariableStore()​ cannot locate another variable within.

If if declare ${VAR1}=  This is ${VAR1}​ and load it into model, as_dict()​ method claims variable cannot be found. But if I pass argument decorated=False​ it gets located.

I want to have a dictionary with all variables in a ROBOT, along with its type, so I can manipulate, add new or whatever else, and ultimately I want to dump ROBOT model into a *.robot​ suite.
________________________________

**Comment by pekkaklarck** [comment]
This code is using Robot's internal modules in ways they aren't designed to be used. If you still need something like this, please submit a new issue proposing APIs that would allow implementing this properly.
