### ISSUE TITLE
RF version 6.1a1 seems not compatible with vscode Robot framework language server v1.10.1

### ISSUE THREAD

**Issue by efrenette11** [robotframework/robotframework#4753]
We I try to debug a test whit Robot framework language server, I get 

Any idea on how to solve thisd issue ?

robot: 2023-05-03 10:30:14 UTC pid: 64689 - Write from robot to dap (_RobotTargetComm) - EXCEPTION - robocorp_ls_core.debug_adapter_core.debug_adapter_threads
Error serializing <robocorp_ls_core.debug_adapter_core.dap.dap_schema.StartSuiteEvent object at 0x7fb11f815340> to json.

Traceback (most recent call last):
  File "/Users/efrenette/.vscode/extensions/robocorp.robotframework-lsp-1.10.1/src/robotframework_ls/vendored/robocorp_ls_core/debug_adapter_core/debug_adapter_threads.py", line 249, in writer_thread
    to_write = to_json(update_ids_to_dap=update_ids_to_dap)
  File "/Users/efrenette/.vscode/extensions/robocorp.robotframework-lsp-1.10.1/src/robotframework_ls/vendored/robocorp_ls_core/debug_adapter_core/dap/dap_base_schema.py", line 36, in to_json
    return json.dumps(self.to_dict(update_ids_to_dap=update_ids_to_dap))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PosixPath is not JSON serializable
robot: 2023-05-03 10:30:17 UTC pid: 64689 - Write from robot to dap (_RobotTargetComm) - EXCEPTION - robocorp_ls_core.debug_adapter_core.debug_adapter_threads
Error serializing <robocorp_ls_core.debug_adapter_core.dap.dap_schema.LogMessageEvent object at 0x7fb11f832280> to json.

**Comment by pekkaklarck** [comment]
The problem seems to be caused by us nowadays using `pathlib.Path` instead of `str` in many places. Changing that back doesn't make sense so this incompatibility should be reported to the language server itself.

**Comment by fabioz** [comment]
Not really... doesn't such a big compatibility breakage warrant a 7.0 release?

**Comment by pekkaklarck** [comment]
I wouldn't change something like this in a bug fix release. in my opinion changing a type of a path from `str` to `pathlib.Path` isn't a big enough change to warrant changing the major version. You may argue that it's against semantic versioning, but we aren't following semver that strictly. If we were, we only could release major versions and bug fix releases. Due to [Hyrum's Law](https://www.hyrumslaw.com/) there are always breaking changes when there are any bigger changes.

**Comment by fabioz** [comment]
I don't even think a major version is needed due to semantic versioning (I'm not too much onto semantic versioning either, but that's beside the point), changing types in the API from `str` to `Path` is a BIG change IMHO and it'll definitely break many libraries...

Anyways, the language server definitely won't work with it for now, I'll have to see when I have time to fix it...
