### ISSUE TITLE
Robot framework 7.x output does not support robot jenkins plugin ?

### ISSUE THREAD

**Issue by sandeshhardikar** [robotframework/robotframework#5018]
Hello,

We have been using [robot jenkins plugin](https://plugins.jenkins.io/robot/) to collect and publish robot framework test results .

With robot framework 7.x coming in , we have a problem with this plugin . 

`Robot results publisher started...
-Parsing output xml:
Done!
-Copying log files to build dir:
Done!
-Assigning results to build:
Error when executing always post condition:
java.lang.NullPointerException
	at java.base/java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1470)
	at java.base/java.text.DateFormat.parse(DateFormat.java:393)
	at hudson.plugins.robot.model.RobotCaseResult.timeDifference(RobotCaseResult.java:68)
	at hudson.plugins.robot.model.RobotCaseResult.getDuration(RobotCaseResult.java:117)
	at hudson.plugins.robot.model.RobotSuiteResult.tally(RobotSuiteResult.java:405)
	at hudson.plugins.robot.model.RobotSuiteResult.tally(RobotSuiteResult.java:413)
	at hudson.plugins.robot.model.RobotResult.tally(RobotResult.java:422)
	at hudson.plugins.robot.RobotBuildAction.setResult(RobotBuildAction.java:124)
	at hudson.plugins.robot.RobotBuildAction.<init>(RobotBuildAction.java:95)
	at hudson.plugins.robot.RobotPublisher.perform(RobotPublisher.java:299)
	at hudson.plugins.robot.RobotStepExecution.run(RobotStepExecution.java:31)
	at hudson.plugins.robot.RobotStepExecution.run(RobotStepExecution.java:14)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)`

This is probably due to dateformat differences between 6.x and 7.x ,see 
![image](https://github.com/robotframework/robotframework/assets/76038578/bf5d1142-9ca5-4a1e-ad25-c5578aa758f7)

I have 2 questions about this 

1. Are there any plans to support robot-framework with this Jenkins plugin ?
2. As a workaround , is it possible that we generate the output with the old timestamp format using `rebot 7.x`

**Comment by pekkaklarck** [comment]
Have you read RF 7 release notes?

**Comment by alangefe** [comment]
@sandeshhardikar , there is an active Pull Request against the Jenkins plugin to address this: https://github.com/jenkinsci/robot-plugin/pull/64

**Comment by pekkaklarck** [comment]
Yes, due to #4258 and some other issues output.xml format changed in backwards incompatible ways. The `--legacy-output` option can be used until tools processing output.xml files have been updated. It has a known problem with Rebot (see #5012), but it will be fixed in RF 7.0.1 most likely next week.

**Comment by pekkaklarck** [comment]
RF 7 comparible Jenkins plugin has been released:
https://github.com/jenkinsci/robot-plugin/releases/tag/robot-3.5.0
