### ISSUE TITLE
Disabling the output file raises an exception 

### ISSUE THREAD

**Issue by d-biehl** [robotframework/robotframework#5228]
Running a suite with disabled output file raises an `AttributeError: 'NoneType' object has no attribute 'as_uri` exception.

Executing this on command line:

```
robot --output NONE tests
```

gives:

```
[ ERROR ] Unexpected error: AttributeError: 'NoneType' object has no attribute 'as_uri'
Traceback (most recent call last):
  File "E:\data\hatch\env\virtual\robotcode\SSe6e0bd\devel.py3.12-rf71\Lib\site-packages\robot\utils\application.py", line 81, in _execute
    rc = self.main(arguments, **options)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\data\hatch\env\virtual\robotcode\SSe6e0bd\devel.py3.12-rf71\Lib\site-packages\robot\run.py", line 463, in main
    result = suite.run(settings)
             ^^^^^^^^^^^^^^^^^^^
  File "E:\data\hatch\env\virtual\robotcode\SSe6e0bd\devel.py3.12-rf71\Lib\site-packages\robot\running\model.py", line 776, in run
    output.close(runner.result)
  File "E:\data\hatch\env\virtual\robotcode\SSe6e0bd\devel.py3.12-rf71\Lib\site-packages\robot\output\output.py", line 58, in close
    LOGGER.output_file(self._settings['Output'])
  File "E:\data\hatch\env\virtual\robotcode\SSe6e0bd\devel.py3.12-rf71\Lib\site-packages\robot\output\logger.py", line 423, in output_file
    logger.output_file(path)
  File "E:\data\hatch\env\virtual\robotcode\SSe6e0bd\devel.py3.12-rf71\Lib\site-packages\robot\output\loggerapi.py", line 172, in output_file
    self.result_file('Output', path)
  File "E:\data\hatch\env\virtual\robotcode\SSe6e0bd\devel.py3.12-rf71\Lib\site-packages\robot\output\console\verbose.py", line 70, in result_file
    self.writer.result_file(kind, path)
  File "E:\data\hatch\env\virtual\robotcode\SSe6e0bd\devel.py3.12-rf71\Lib\site-packages\robot\output\console\verbose.py", line 150, in result_file
    self.stdout.result_file(kind, path)
  File "E:\data\hatch\env\virtual\robotcode\SSe6e0bd\devel.py3.12-rf71\Lib\site-packages\robot\output\console\highlighting.py", line 122, in result_file
    path = self._highlighter.link(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\data\hatch\env\virtual\robotcode\SSe6e0bd\devel.py3.12-rf71\Lib\site-packages\robot\output\console\highlighting.py", line 162, in link
    uri = path.as_uri()
          ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'as_uri'

```

disabling `--report` and `--log` works.

Robot Framework Version: 7.1

**Comment by rarajabs** [comment]
related to #5205

**Comment by d-biehl** [comment]
ok, did not found it because it is already fixed ;-)
