### ISSUE TITLE
robot not generate log.html and report.html when exception raised by python lib

### ISSUE THREAD

**Issue by allenyllee** [robotframework/robotframework#5278]
During running test case, when test case failed with exception error raising by the python lib, the robot seems terminated by itself.

Here is the partial error message shown in console log:

```
[ ERROR ] Initializing library 'Redfish' with arguments [ https://10.1.50.248:443 | root | 0penBmc ] failed: RetriesExhaustedError
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/vscode/.local/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/vscode/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/vscode/.local/lib/python3.11/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x708e8914be10>: Failed to establish a new connection: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.1.50.248', port=443): Max retries exceeded with url: /redfish/v1/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x708e8914be10>: Failed to establish a new connection: [Errno 113] No route to host'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.11/site-packages/redfish/rest/v1.py", line 915, in _rest_request
    resp = self._session.request(method.upper(), "{}{}".format(self.__base_url, reqpath), data=body,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='10.1.50.248', port=443): Max retries exceeded with url: /redfish/v1/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x708e8914be10>: Failed to establish a new connection: [Errno 113] No route to host'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/lib/bmc_redfish.py", line 50, in __init__
    super(bmc_redfish, self).__init__(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.11/site-packages/redfish/rest/v1.py", line 1080, in __init__
    super(HttpClient, self).__init__(base_url, username=username,
  File "/home/vscode/.local/lib/python3.11/site-packages/redfish/rest/v1.py", line 505, in __init__
    self.get_root_object()
  File "/home/vscode/.local/lib/python3.11/site-packages/redfish/rest/v1.py", line 597, in get_root_object
    raise excp
  File "/home/vscode/.local/lib/python3.11/site-packages/redfish/rest/v1.py", line 595, in get_root_object
    resp = self.get(self.default_prefix)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/lib/redfish_plus.py", line 133, in get
    return self.rest_request(super(redfish_plus, self).get, *args,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/lib/redfish_plus.py", line 123, in rest_request
    response = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/redfish/rest/v1.py", line 633, in get
    return self._rest_request(path, method='GET', args=args,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/redfish/rest/v1.py", line 1118, in _rest_request
    return super(HttpClient, self)._rest_request(path=path, method=method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/redfish/rest/v1.py", line 959, in _rest_request
    raise RetriesExhaustedError() from cause_exception
redfish.rest.v1.RetriesExhaustedError

Try --help for usage information.
```

This error indicate that the redfish python lib encounter some network issue, it retries many times and raise exception.

I also try to regenerate report.html by execute `rebot output.xml`, but it says:
```
[ ERROR ] Reading XML source 'output.xml' failed: Incompatible child element 'errors' for 'suite'.

Try --help for usage information.
```

Here is the output.xml:
[output (複製).zip](https://github.com/user-attachments/files/17942050/output.zip)

**Comment by pekkaklarck** [comment]
For some reason the whole execution crashes when initializing the library as part of the importing process fails. This shouldn't happen, we have tests for handling errors like this so that execution can continue normally. I also tested this separately with a simple library that has a failing `__init__`. I even tried raising `redfish.rest.v1.RetriesExhaustedError` to see is that exception somehow special, but also that was handled fine.

Can you provide a simple example I could use to reproduce this? Also, what Robot Framework version did you use?

**Comment by pekkaklarck** [comment]
Any new info related to this? I cannot reproduce the problem so if there's no updates I cannot do anything else than close this issue.

**Comment by pekkaklarck** [comment]
No updates, closing.

**Comment by allenyllee** [comment]
> Can you provide a simple example I could use to reproduce this? Also, what Robot Framework version did you use?

I ran into this issue again. The problem occurs when the BMC IP changes during testing. For example, if a test case switches the BMC IP from static to DHCP, the IP address updates, but the `Redfish.Get` method still tries to connect using the old static IP, resulting in a `RetriesExhaustedError`.

```
$ python3 --version
Python 3.10.12
```

```
$ pip list

Package                            Version
---------------------------------- -----------
argcomplete                        3.5.3
attrs                              25.1.0
bcrypt                             4.3.0
beautifulsoup4                     4.13.3
cached-property                    2.0.1
certifi                            2025.1.31
cffi                               1.17.1
chardet                            3.0.4
charset-normalizer                 3.4.1
click                              8.1.8
colorama                           0.4.6
commitizen                         4.4.1
cryptography                       43.0.3
cz-conventional-gitmoji            0.6.1
dbus-python                        1.2.18
decli                              0.6.2
decorator                          5.2.1
defusedxml                         0.7.1
distro                             1.7.0
dnspython                          2.7.0
docutils                           0.21.2
et_xmlfile                         2.0.0
exceptiongroup                     1.2.2
exchangelib                        5.5.0
fonttools                          4.56.0
fpdf2                              2.7.5
furl                               2.1.3
graphviz                           0.13.2
h11                                0.14.0
holidays                           0.45
htmldocx                           0.0.6
idna                               3.10
importlib_metadata                 8.6.1
isodate                            0.7.2
java-access-bridge-wrapper         1.2.0
Jinja2                             3.1.5
jsonpatch                          1.33
jsonpath-ng                        1.7.0
jsonpath-rw                        1.4.0
jsonpointer                        3.0.0
jsonschema                         4.23.0
jsonschema-specifications          2024.10.1
lxml                               5.3.1
markdown-it-py                     3.0.0
MarkupSafe                         3.0.2
mdurl                              0.1.2
more-itertools                     10.6.0
mss                                6.1.0
netsuitesdk                        1.24.0
notifiers                          1.3.3
numpy                              1.26.4
O365                               2.0.26
oauthlib                           3.2.2
opencv-python-headless             4.8.1.78
openpyxl                           3.1.5
orderedmultidict                   1.0.1
outcome                            1.3.0.post0
packaging                          24.2
paramiko                           3.5.1
pathspec                           0.12.1
pdfminer.six                       20221105
pendulum                           3.0.0
pillow                             10.4.0
pip                                22.0.2
platformdirs                       4.3.6
ply                                3.11
prompt_toolkit                     3.0.50
pycparser                          2.22
Pygments                           2.19.1
PyGObject                          3.42.1
PyJWT                              2.10.1
PyNaCl                             1.5.0
pynput-robocorp-fork               5.0.0
pyotp                              2.9.0
pypdf                              3.17.4
pyperclip                          1.9.0
PySocks                            1.7.1
pyspnego                           0.11.2
pytesseract                        0.3.13
python-dateutil                    2.9.0.post0
python-docx                        0.8.11
python-dotenv                      1.0.1
python-xlib                        0.33
pytz                               2025.1
pytz-deprecation-shim              0.1.0.post0
PyYAML                             5.4.1
questionary                        2.1.0
redfish                            3.2.8
redfish_utilities                  3.3.8
redfishtool                        1.1.8
referencing                        0.36.2
requests                           2.32.3
requests-file                      2.1.0
requests_ntlm                      1.3.0
requests-oauthlib                  1.3.1
requests-toolbelt                  1.0.0
requests-unixsocket                0.3.0
rich                               13.9.4
rich-click                         1.8.5
robocorp-storage                   1.0.5
robotframework                     7.2.2
robotframework-angularjs           1.0.0
robotframework-csvlibrary          0.0.5
robotframework-pythonlibcore       4.4.1
robotframework-requests            0.9.7
robotframework-scplibrary          1.2.0
robotframework-seleniumlibrary     6.7.1
robotframework-seleniumtestability 2.1.0
robotframework-sshlibrary          3.8.0
robotframework-tidy                4.16.0
robotframework-xvfb                1.2.2
rpaframework                       30.0.0
rpaframework-core                  12.0.1
rpaframework-pdf                   8.0.0
rpaframework-recognition           6.0.0
rpds-py                            0.23.1
scp                                0.15.0
selenium                           4.15.2
setuptools                         59.6.0
simple-salesforce                  1.12.6
six                                1.17.0
smartsheet-python-sdk              3.0.2
sniffio                            1.3.1
sortedcontainers                   2.4.0
soupsieve                          2.6
ssh-import-id                      5.11
stringcase                         1.2.0
tenacity                           8.5.0
termcolor                          2.5.0
time-machine                       2.16.0
tomli                              2.2.1
tomlkit                            0.13.2
trio                               0.29.0
trio-websocket                     0.12.2
tweepy                             3.10.0
typing_extensions                  4.12.2
tzdata                             2025.1
tzlocal                            4.3.1
ufw                                0.36.1
urllib3                            1.26.15
validators                         0.34.0
wcwidth                            0.2.13
webdriver-manager                  4.0.2
wheel                              0.37.1
wrapt                              1.17.2
wsproto                            1.2.0
xlrd                               2.0.1
XlsxWriter                         3.2.2
xlutils                            2.0.0
xlwt                               1.3.0
xvfbwrapper                        0.2.9
zeep                               4.3.1
zipp                               3.21.0
```
