### ISSUE TITLE
Logging changes break the robot backgoundlogger

### ISSUE THREAD

**Issue by jaltendorfer** [robotframework/robotframework#5293]
The changes in #5255 break the robot backgoundlogger. The import of the backgroundlogger failes:
```
Traceback (most recent call last):
  File "/home/user/test/TestLib.py", line 2, in <module>
    from robotbackgroundlogger import BackgroundLogger
  File "/home/user/test/.venv/lib/python3.10/site-packages/robotbackgroundlogger.py", line 57, in <module>
    class BackgroundLogger(BaseLogger):
  File "/home/user/test/.venv/lib/python3.10/site-packages/robotbackgroundlogger.py", line 75, in BackgroundLogger
    LOGGING_THREADS = logger.librarylogger.LOGGING_THREADS
AttributeError: module 'robot.output.librarylogger' has no attribute 'LOGGING_THREADS'
```

**Comment by pekkaklarck** [comment]
Thanks for the report. I fixed the problem by reintroducing the `LOGGING_THREADS` constant.
